/*
%## Copyright (C) 2008, 2016 S.Box
%## 
%## This program is free software; you can redistribute it and/or modify
%## it under the terms of the GNU General Public License as published by
%## the Free Software Foundation; either version 2 of the License, or
%## (at your option) any later version.
%## 
%## This program is distributed in the hope that it will be useful,
%## but WITHOUT ANY WARRANTY; without even the implied warranty of
%## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%## GNU General Public License for more details.
%## 
%## You should have received a copy of the GNU General Public License
%## along with this program; if not, write to the Free Software
%## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

%## ascent_variables.m

%## Author: S.Box
%## Created: 2010-05-27
/*
 * BodyTubeDialog.java
 *
 * Created on 29 April 2009, 13:41
 */

package net.sf.openrocket.camrocksim;

import java.util.Vector;

import javax.swing.JOptionPane;

/**
 *
 * @author  sb4p07
 */
public class BodyTubeDialog extends javax.swing.JDialog {
	
	//**Class Members
	double length,
			ID,
			OD,
			Mass,
			Position;
	boolean ReadOk;
	String Name;
	
	/** Creates new form BodyTubeDialog */
	public BodyTubeDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		
		BTubeSpecTitle = new javax.swing.JLabel();
		BTubeNameLabel = new javax.swing.JLabel();
		BTubeLengthLabel = new javax.swing.JLabel();
		BTubeIDLabel = new javax.swing.JLabel();
		BTubeODLable = new javax.swing.JLabel();
		BTubeMassLabel = new javax.swing.JLabel();
		BTubePosLabel = new javax.swing.JLabel();
		BTubeNameText = new javax.swing.JTextField();
		BTubeLengthText = new javax.swing.JTextField();
		BTubeIDText = new javax.swing.JTextField();
		BTubeODText = new javax.swing.JTextField();
		BTubeMassText = new javax.swing.JTextField();
		BTubePosText = new javax.swing.JTextField();
		BTubeLengthUnit = new javax.swing.JLabel();
		BTubeIDUnit = new javax.swing.JLabel();
		BTubeODUnit = new javax.swing.JLabel();
		BTubeMassUnit = new javax.swing.JLabel();
		BTubePosUnit = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		
		BTubeSpecTitle.setText("Set body tube specifications");
		
		BTubeNameLabel.setText("Name");
		
		BTubeLengthLabel.setText("Length");
		
		BTubeIDLabel.setText("Inner Diameter");
		
		BTubeODLable.setText("Outer Diameter");
		
		BTubeMassLabel.setText("Mass");
		
		BTubePosLabel.setText("Position");
		
		BTubeNameText.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				BTubeNameTextFocusLost(evt);
			}
		});
		
		BTubeLengthText.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				BTubeLengthTextFocusLost(evt);
			}
		});
		
		BTubeIDText.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				BTubeIDTextFocusLost(evt);
			}
		});
		
		BTubeODText.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				BTubeODTextFocusLost(evt);
			}
		});
		
		BTubeMassText.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				BTubeMassTextFocusLost(evt);
			}
		});
		
		BTubePosText.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				BTubePosTextFocusLost(evt);
			}
		});
		
		BTubeLengthUnit.setText("m");
		
		BTubeIDUnit.setText("m");
		
		BTubeODUnit.setText("m");
		
		BTubeMassUnit.setText("kg");
		
		BTubePosUnit.setText("m");
		
		jButton1.setText("Add");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		
		jButton2.setText("Cancel");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		
		jButton3.setText("?");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(BTubeSpecTitle)
										.addGroup(layout.createSequentialGroup()
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(BTubeNameLabel)
														.addComponent(BTubeLengthLabel)
														.addComponent(BTubeIDLabel)
														.addComponent(BTubeODLable)
														.addComponent(BTubeMassLabel)
														.addComponent(BTubePosLabel))
												.addGap(49, 49, 49)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
														.addComponent(BTubeNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
														.addComponent(BTubeLengthText)
														.addComponent(BTubeIDText)
														.addComponent(BTubeODText)
														.addComponent(BTubeMassText)
														.addComponent(BTubePosText))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(BTubePosUnit)
														.addComponent(BTubeMassUnit)
														.addComponent(BTubeODUnit)
														.addComponent(BTubeIDUnit)
														.addComponent(BTubeLengthUnit))))
								.addGap(37, 37, 37))
						.addGroup(layout.createSequentialGroup()
								.addGap(52, 52, 52)
								.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
								.addGap(66, 66, 66)));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(BTubeSpecTitle)
								.addGap(36, 36, 36)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(BTubeNameLabel)
										.addComponent(BTubeNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(BTubeLengthLabel)
										.addComponent(BTubeLengthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(BTubeLengthUnit))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(BTubeIDLabel)
										.addComponent(BTubeIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(BTubeIDUnit))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(BTubeODLable)
										.addComponent(BTubeODText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(BTubeODUnit))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(BTubeMassLabel)
										.addComponent(BTubeMassText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(BTubeMassUnit))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(BTubePosLabel)
										.addComponent(BTubePosText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(BTubePosUnit))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jButton1)
										.addComponent(jButton2)
										.addComponent(jButton3))
								.addGap(23, 23, 23)));
		
		pack();
	}// </editor-fold>//GEN-END:initComponents
	
	private void BTubeLengthTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BTubeLengthTextFocusLost
		//Function to test the validity of the user input
		TestUserTextInput LengthTest = new TestUserTextInput(BTubeLengthText);
		length = LengthTest.TestDouble();
		BTubeLengthText = LengthTest.InputField;
	}//GEN-LAST:event_BTubeLengthTextFocusLost
	
	private void BTubeIDTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BTubeIDTextFocusLost
		///Function to test the validity of the user input
		TestUserTextInput IDTest = new TestUserTextInput(BTubeIDText);
		ID = IDTest.TestDouble();
		BTubeIDText = IDTest.InputField;
	}//GEN-LAST:event_BTubeIDTextFocusLost
	
	private void BTubeODTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BTubeODTextFocusLost
		///Function to test the validity of the user input
		TestUserTextInput ODTest = new TestUserTextInput(BTubeODText);
		OD = ODTest.TestDouble();
		BTubeODText = ODTest.InputField;
	}//GEN-LAST:event_BTubeODTextFocusLost
	
	private void BTubeMassTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BTubeMassTextFocusLost
		///Function to test the validity of the user input
		TestUserTextInput MassTest = new TestUserTextInput(BTubeMassText);
		Mass = MassTest.TestDouble();
		BTubeMassText = MassTest.InputField;
	}//GEN-LAST:event_BTubeMassTextFocusLost
	
	private void BTubePosTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BTubePosTextFocusLost
		///Function to test the validity of the user input
		TestUserTextInput PositionTest = new TestUserTextInput(BTubePosText);
		Position = PositionTest.TestDouble();
		BTubePosText = PositionTest.InputField;
	}//GEN-LAST:event_BTubePosTextFocusLost
	
	private void BTubeNameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BTubeNameTextFocusLost
		// TODO add your handling code here:
		Name = BTubeNameText.getText();
	}//GEN-LAST:event_BTubeNameTextFocusLost
	
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
		this.dispose();
	}//GEN-LAST:event_jButton2ActionPerformed
	
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		boolean Goer = CheckValidity();
		if (Goer == true) {
			ReadOk = true;
			this.dispose();
		} else {
			JOptionPane.showMessageDialog(null, ("Something is wrong with the data that you entered"));
		}
	}//GEN-LAST:event_jButton1ActionPerformed
	
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
		Tips tDiag = new Tips(null, true);
		tDiag.setTipTxt(
				"Body Tube Settings \n\n Use this window to specify the parameters of the body part. Position is the distance, along the rocket's axis, from the nose tip to the foremost edge of the part.");
		tDiag.setVisible(true);
	}//GEN-LAST:event_jButton3ActionPerformed
	
	private boolean CheckValidity() {
		boolean answer;
		Vector<javax.swing.JTextField> FieldsList = new Vector<javax.swing.JTextField>();
		FieldsList.add(BTubeLengthText);
		FieldsList.add(BTubeIDText);
		FieldsList.add(BTubeODText);
		FieldsList.add(BTubeMassText);
		FieldsList.add(BTubePosText);
		
		TestUserTextInput TUI1 = new TestUserTextInput(FieldsList);
		answer = TUI1.TestDoubleList();
		return (answer);
	}
	
	/**
	* @param args the command line arguments
	*/
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				BodyTubeDialog dialog = new BodyTubeDialog(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}
	
	public void FillFields(double d1, double d2, double d3, double d4, double d5, String s1) {
		length = d1;
		ID = d2;
		OD = d3;
		Mass = d4;
		Position = d5;
		Name = s1;
		BTubeLengthText.setText(Double.toString(length));
		BTubeIDText.setText(Double.toString(ID));
		BTubeODText.setText(Double.toString(OD));
		BTubeMassText.setText(Double.toString(Mass));
		BTubePosText.setText(Double.toString(Position));
		BTubeNameText.setText(Name);
		
		
	}
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel BTubeIDLabel;
	private javax.swing.JTextField BTubeIDText;
	private javax.swing.JLabel BTubeIDUnit;
	private javax.swing.JLabel BTubeLengthLabel;
	private javax.swing.JTextField BTubeLengthText;
	private javax.swing.JLabel BTubeLengthUnit;
	private javax.swing.JLabel BTubeMassLabel;
	private javax.swing.JTextField BTubeMassText;
	private javax.swing.JLabel BTubeMassUnit;
	private javax.swing.JLabel BTubeNameLabel;
	private javax.swing.JTextField BTubeNameText;
	private javax.swing.JLabel BTubeODLable;
	private javax.swing.JTextField BTubeODText;
	private javax.swing.JLabel BTubeODUnit;
	private javax.swing.JLabel BTubePosLabel;
	private javax.swing.JTextField BTubePosText;
	private javax.swing.JLabel BTubePosUnit;
	private javax.swing.JLabel BTubeSpecTitle;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	// End of variables declaration//GEN-END:variables
	
}
