/*
%## Copyright (C) 2010, 2016 S.Box
%## 
%## This program is free software; you can redistribute it and/or modify
%## it under the terms of the GNU General Public License as published by
%## the Free Software Foundation; either version 2 of the License, or
%## (at your option) any later version.
%## 
%## This program is distributed in the hope that it will be useful,
%## but WITHOUT ANY WARRANTY; without even the implied warranty of
%## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%## GNU General Public License for more details.
%## 
%## You should have received a copy of the GNU General Public License
%## along with this program; if not, write to the Free Software
%## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

%## ConeDialog.java

%## Author: S.Box
%## Created: 2010-05-27
/*
 * ConeDialog.java
 *
 * Created on 14 April 2009, 17:02
 */

package net.sf.openrocket.camrocksim;

import java.util.Vector;

/**
 *
 * @author  simon
 */
public class ConeDialog extends javax.swing.JDialog {
	//*Class Members
	double Length, Diameter, Mass, Position;
	boolean ReadOk;
	String Name;
	
	/** Creates new form ConeDialog */
	public ConeDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		
		ConeTitleLabel = new javax.swing.JLabel();
		ConeLengthLabel = new javax.swing.JLabel();
		ConeDiameterLabel = new javax.swing.JLabel();
		ConeMassLabel = new javax.swing.JLabel();
		ConePositionLabel = new javax.swing.JLabel();
		ConeLengthBox = new javax.swing.JTextField();
		ConeDiameterBox = new javax.swing.JTextField();
		ConeMassBox = new javax.swing.JTextField();
		ConePositionBox = new javax.swing.JTextField();
		ConeLengthDim = new javax.swing.JLabel();
		ConeDiameterDim = new javax.swing.JLabel();
		ConeMassDim = new javax.swing.JLabel();
		ConePositionDim = new javax.swing.JLabel();
		AddConeDataButton = new javax.swing.JButton();
		ConeCancelButton = new javax.swing.JButton();
		ValidityLabel = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Cone data dialog");
		
		ConeTitleLabel.setText("Set cone specifications");
		
		ConeLengthLabel.setText("Length");
		
		ConeDiameterLabel.setText("Base Diameter");
		
		ConeMassLabel.setText("Mass");
		
		ConePositionLabel.setText("Position");
		
		ConeLengthBox.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				ConeLengthBoxFocusGained(evt);
			}
			
			public void focusLost(java.awt.event.FocusEvent evt) {
				ConeLengthBoxFocusLost(evt);
			}
		});
		
		ConeDiameterBox.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				ConeDiameterBoxFocusGained(evt);
			}
			
			public void focusLost(java.awt.event.FocusEvent evt) {
				ConeDiameterBoxFocusLost(evt);
			}
		});
		
		ConeMassBox.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				ConeMassBoxFocusGained(evt);
			}
			
			public void focusLost(java.awt.event.FocusEvent evt) {
				ConeMassBoxFocusLost(evt);
			}
		});
		
		ConePositionBox.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				ConePositionBoxFocusGained(evt);
			}
			
			public void focusLost(java.awt.event.FocusEvent evt) {
				ConePositionBoxFocusLost(evt);
			}
		});
		
		ConeLengthDim.setText("m");
		
		ConeDiameterDim.setText("m");
		
		ConeMassDim.setText("kg");
		
		ConePositionDim.setText("m");
		
		AddConeDataButton.setText("Add");
		AddConeDataButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				AddConeDataButtonActionPerformed(evt);
			}
		});
		
		ConeCancelButton.setText("Cancel");
		ConeCancelButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ConeCancelButtonActionPerformed(evt);
			}
		});
		
		ValidityLabel.setForeground(java.awt.Color.red);
		
		jLabel1.setText("Name");
		
		jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				jTextField1FocusLost(evt);
			}
		});
		
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(ConeTitleLabel)
												.addGap(57, 57, 57))
										.addComponent(jLabel1)
										.addGroup(layout.createSequentialGroup()
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup()
																.addGap(65, 65, 65)
																.addComponent(AddConeDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(ConeCancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
																.addGap(82, 82, 82))
														.addComponent(ValidityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
														.addGroup(layout.createSequentialGroup()
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(ConeLengthLabel)
																		.addComponent(ConeDiameterLabel)
																		.addComponent(ConeMassLabel)
																		.addComponent(ConePositionLabel))
																.addGap(35, 35, 35)
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																		.addComponent(ConePositionBox)
																		.addComponent(ConeMassBox)
																		.addComponent(ConeDiameterBox)
																		.addComponent(ConeLengthBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 86,
																				Short.MAX_VALUE)
																		.addComponent(jTextField1))
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(ConeMassDim)
																		.addComponent(ConePositionDim)
																		.addComponent(ConeDiameterDim)
																		.addComponent(ConeLengthDim))
																.addGap(45, 45, 45)))
												.addContainerGap()))));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(ConeTitleLabel)
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel1)
										.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(ConeLengthDim)
										.addComponent(ConeLengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(ConeLengthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(ConeDiameterLabel)
										.addComponent(ConeDiameterDim)
										.addComponent(ConeDiameterBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(ConeMassLabel)
										.addComponent(ConeMassDim, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(ConeMassBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(ConePositionLabel)
										.addComponent(ConePositionDim)
										.addComponent(ConePositionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(ValidityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(24, 24, 24)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(AddConeDataButton)
										.addComponent(ConeCancelButton))
								.addContainerGap(25, Short.MAX_VALUE)));
		
		pack();
	}// </editor-fold>//GEN-END:initComponents
	
	private void ConeLengthBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConeLengthBoxFocusLost
		//Function to test the validity of the user input
		TestUserTextInput LengthTest = new TestUserTextInput(ConeLengthBox);
		Length = LengthTest.TestDouble();
		ConeLengthBox = LengthTest.InputField;
	}//GEN-LAST:event_ConeLengthBoxFocusLost
	
	private void ConeDiameterBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConeDiameterBoxFocusLost
		//Function to test the validity of the user input
		TestUserTextInput DiameterTest = new TestUserTextInput(ConeDiameterBox);
		Length = DiameterTest.TestDouble();
		ConeDiameterBox = DiameterTest.InputField;
	}//GEN-LAST:event_ConeDiameterBoxFocusLost
	
	private void ConeMassBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConeMassBoxFocusLost
		//Function to test the validity of the user input
		TestUserTextInput MassTest = new TestUserTextInput(ConeMassBox);
		Length = MassTest.TestDouble();
		ConeMassBox = MassTest.InputField;
	}//GEN-LAST:event_ConeMassBoxFocusLost
	
	private void ConePositionBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConePositionBoxFocusLost
		//Function to test the validity of the user input
		TestUserTextInput PositionTest = new TestUserTextInput(ConePositionBox);
		Length = PositionTest.TestDouble();
		ConePositionBox = PositionTest.InputField;
	}//GEN-LAST:event_ConePositionBoxFocusLost
	
	private void ConeCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConeCancelButtonActionPerformed
		// TODO add your handling code here:
		this.dispose();
	}//GEN-LAST:event_ConeCancelButtonActionPerformed
	
	private void AddConeDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddConeDataButtonActionPerformed
		// TODO add your handling code here:
		boolean Goer = CheckValidity();
		if (Goer == true) {
			ReadOk = true;
			this.dispose();
		} else {
			ValidityLabel.setText("Warning: One or more entries are invalid");
		}
		
	}//GEN-LAST:event_AddConeDataButtonActionPerformed
	
	private void ConeLengthBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConeLengthBoxFocusGained
		// TODO add your handling code here:
		ConeLengthBox.setForeground(java.awt.Color.BLACK);
	}//GEN-LAST:event_ConeLengthBoxFocusGained
	
	private void ConeDiameterBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConeDiameterBoxFocusGained
		// TODO add your handling code here:
		ConeDiameterBox.setForeground(java.awt.Color.BLACK);
	}//GEN-LAST:event_ConeDiameterBoxFocusGained
	
	private void ConeMassBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConeMassBoxFocusGained
		// TODO add your handling code here:
		ConeMassBox.setForeground(java.awt.Color.BLACK);
	}//GEN-LAST:event_ConeMassBoxFocusGained
	
	private void ConePositionBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConePositionBoxFocusGained
		// TODO add your handling code here:
		ConePositionBox.setForeground(java.awt.Color.BLACK);
	}//GEN-LAST:event_ConePositionBoxFocusGained
	
	private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
		// TODO add your handling code here:
		Name = jTextField1.getText();
	}//GEN-LAST:event_jTextField1FocusLost
	
	
	private boolean CheckValidity() {
		boolean answer;
		Vector<javax.swing.JTextField> FieldsList = new Vector<javax.swing.JTextField>();
		FieldsList.add(ConeLengthBox);
		FieldsList.add(ConeDiameterBox);
		FieldsList.add(ConeMassBox);
		FieldsList.add(ConePositionBox);
		
		TestUserTextInput TUI1 = new TestUserTextInput(FieldsList);
		answer = TUI1.TestDoubleList();
		return (answer);
	}
	
	/**
	* @param args the command line arguments
	*/
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				ConeDialog dialog = new ConeDialog(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}
	
	public void FillFields(double d1, double d2, double d3, double d4, String S1) {
		Length = d1;
		Diameter = d2;
		Mass = d3;
		Position = d4;
		Name = S1;
		
		ConeLengthBox.setText(Double.toString(Length));
		ConeDiameterBox.setText(Double.toString(Diameter));
		ConePositionBox.setText(Double.toString(Position));
		ConeMassBox.setText(Double.toString(Mass));
		jTextField1.setText(Name);
	}
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton AddConeDataButton;
	private javax.swing.JButton ConeCancelButton;
	private javax.swing.JTextField ConeDiameterBox;
	private javax.swing.JLabel ConeDiameterDim;
	private javax.swing.JLabel ConeDiameterLabel;
	private javax.swing.JTextField ConeLengthBox;
	private javax.swing.JLabel ConeLengthDim;
	private javax.swing.JLabel ConeLengthLabel;
	private javax.swing.JTextField ConeMassBox;
	private javax.swing.JLabel ConeMassDim;
	private javax.swing.JLabel ConeMassLabel;
	private javax.swing.JTextField ConePositionBox;
	private javax.swing.JLabel ConePositionDim;
	private javax.swing.JLabel ConePositionLabel;
	private javax.swing.JLabel ConeTitleLabel;
	private javax.swing.JLabel ValidityLabel;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables
	
}
