/*
%## Copyright (C) 2010, 2016 S.Box
%## 
%## This program is free software; you can redistribute it and/or modify
%## it under the terms of the GNU General Public License as published by
%## the Free Software Foundation; either version 2 of the License, or
%## (at your option) any later version.
%## 
%## This program is distributed in the hope that it will be useful,
%## but WITHOUT ANY WARRANTY; without even the implied warranty of
%## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%## GNU General Public License for more details.
%## 
%## You should have received a copy of the GNU General Public License
%## along with this program; if not, write to the Free Software
%## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

%## Cylinder Dialog.java

%## Author: S.Box
%## Created: 2010-05-27
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CylinderDialog.java
 *
 * Created on 24-Jan-2010, 12:47:14
 */

package net.sf.openrocket.camrocksim;

import java.util.Vector;

import javax.swing.JOptionPane;

/**
 *
 * @author simon
 */
public class CylinderDialog extends javax.swing.JDialog {
	
	//**Class Members
	double length,
			Diameter,
			Mass,
			Position,
			RadialPosition;
	boolean ReadOk;
	String Name;
	
	/** Creates new form CylinderDialog */
	public CylinderDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		
		CylMassUnit = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		CylDUnit = new javax.swing.JLabel();
		CylPosText = new javax.swing.JTextField();
		CylLengthUnit = new javax.swing.JLabel();
		CylODText = new javax.swing.JTextField();
		CylMassText = new javax.swing.JTextField();
		CylLengthText = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		CylSpecTitle = new javax.swing.JLabel();
		CylPosUnit = new javax.swing.JLabel();
		CylNameText = new javax.swing.JTextField();
		CylDLable = new javax.swing.JLabel();
		CylLengthLabel = new javax.swing.JLabel();
		CylNameLabel = new javax.swing.JLabel();
		CylPosLabel = new javax.swing.JLabel();
		CylMassLabel = new javax.swing.JLabel();
		CylRadPosLabel = new javax.swing.JLabel();
		CylRadPosText = new javax.swing.JTextField();
		CylRadPosUnit = new javax.swing.JLabel();
		jButton3 = new javax.swing.JButton();
		
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		
		CylMassUnit.setText("kg");
		
		jButton2.setText("Cancel");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		
		CylDUnit.setText("m");
		
		CylPosText.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				CylPosTextFocusLost(evt);
			}
		});
		
		CylLengthUnit.setText("m");
		
		CylODText.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				CylODTextFocusLost(evt);
			}
		});
		
		CylMassText.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				CylMassTextFocusLost(evt);
			}
		});
		
		CylLengthText.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				CylLengthTextFocusLost(evt);
			}
		});
		
		jButton1.setText("Add");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		
		CylSpecTitle.setText("Set cylinder specifications");
		
		CylPosUnit.setText("m");
		
		CylNameText.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				CylNameTextFocusLost(evt);
			}
		});
		
		CylDLable.setText("Diameter");
		
		CylLengthLabel.setText("Length");
		
		CylNameLabel.setText("Name");
		
		CylPosLabel.setText("Position");
		
		CylMassLabel.setText("Mass");
		
		CylRadPosLabel.setText("Radial Position");
		
		CylRadPosText.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				CylRadPosTextFocusLost(evt);
			}
		});
		
		CylRadPosUnit.setText("m");
		
		jButton3.setText("?");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(CylRadPosLabel)
								.addContainerGap(247, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup()
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(CylDLable)
																.addComponent(CylMassLabel)
																.addComponent(CylPosLabel)
																.addComponent(CylLengthLabel))
														.addGap(49, 49, 49)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																		.addComponent(CylLengthText)
																		.addComponent(CylODText)
																		.addComponent(CylMassText)
																		.addComponent(CylPosText)
																		.addComponent(CylNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addComponent(CylRadPosText, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(CylMassUnit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																.addComponent(CylPosUnit, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
																.addComponent(CylLengthUnit)
																.addComponent(CylDUnit, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
																.addComponent(CylRadPosUnit)))
												.addComponent(CylNameLabel)
												.addComponent(CylSpecTitle)))
								.addContainerGap(66, Short.MAX_VALUE)));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGap(24, 24, 24)
								.addComponent(CylSpecTitle)
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(layout.createSequentialGroup()
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(CylNameLabel)
														.addComponent(CylNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(CylLengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(CylLengthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addComponent(CylLengthUnit))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(CylDLable)
										.addComponent(CylODText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(CylDUnit))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(CylMassLabel)
										.addComponent(CylMassText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(CylMassUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(CylPosLabel)
										.addComponent(CylPosText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(CylPosUnit))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(CylRadPosLabel)
										.addComponent(CylRadPosUnit)
										.addComponent(CylRadPosText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(49, 49, 49)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jButton1)
										.addComponent(jButton2)
										.addComponent(jButton3))
								.addContainerGap()));
		
		pack();
	}// </editor-fold>//GEN-END:initComponents
	
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
		this.dispose();
	}//GEN-LAST:event_jButton2ActionPerformed
	
	private void CylPosTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CylPosTextFocusLost
		///Function to test the validity of the user input
		TestUserTextInput PositionTest = new TestUserTextInput(CylPosText);
		Position = PositionTest.TestDouble();
		CylPosText = PositionTest.InputField;
	}//GEN-LAST:event_CylPosTextFocusLost
	
	private void CylODTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CylODTextFocusLost
		///Function to test the validity of the user input
		TestUserTextInput ODTest = new TestUserTextInput(CylODText);
		Diameter = ODTest.TestDouble();
		CylODText = ODTest.InputField;
	}//GEN-LAST:event_CylODTextFocusLost
	
	private void CylMassTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CylMassTextFocusLost
		///Function to test the validity of the user input
		TestUserTextInput MassTest = new TestUserTextInput(CylMassText);
		Mass = MassTest.TestDouble();
		CylMassText = MassTest.InputField;
	}//GEN-LAST:event_CylMassTextFocusLost
	
	private void CylLengthTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CylLengthTextFocusLost
		//Function to test the validity of the user input
		TestUserTextInput LengthTest = new TestUserTextInput(CylLengthText);
		length = LengthTest.TestDouble();
		CylLengthText = LengthTest.InputField;
	}//GEN-LAST:event_CylLengthTextFocusLost
	
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		
		boolean Goer = CheckValidity();
		if (Goer == true) {
			ReadOk = true;
			this.dispose();
		} else {
			JOptionPane.showMessageDialog(null, ("Something is wrong with the data that you entered"));
			;
		}
	}//GEN-LAST:event_jButton1ActionPerformed
	
	private void CylNameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CylNameTextFocusLost
		// TODO add your handling code here:
		Name = CylNameText.getText();
	}//GEN-LAST:event_CylNameTextFocusLost
	
	private void CylRadPosTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CylRadPosTextFocusLost
		// TODO add your handling code here:
		///Function to test the validity of the user input
		TestUserTextInput RadPosTest = new TestUserTextInput(CylRadPosText);
		RadialPosition = RadPosTest.TestDouble();
		CylRadPosText = RadPosTest.InputField;
	}//GEN-LAST:event_CylRadPosTextFocusLost
	
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
		Tips tDiag = new Tips(null, true);
		tDiag.setTipTxt(
				"Cylinder Settings \n\n Use this window to specify the parameters of the Cylinder part. Position is the distance, along the rocket's axis, from the nose tip to the foremost edge of the part. Radial position is the offset between the centre of the part and the rocket's axis. ");
		tDiag.setVisible(true);
	}//GEN-LAST:event_jButton3ActionPerformed
	
	
	private boolean CheckValidity() {
		boolean answer;
		Vector<javax.swing.JTextField> FieldsList = new Vector<javax.swing.JTextField>();
		FieldsList.add(CylLengthText);
		FieldsList.add(CylODText);
		FieldsList.add(CylMassText);
		FieldsList.add(CylPosText);
		FieldsList.add(CylRadPosText);
		
		TestUserTextInput TUI1 = new TestUserTextInput(FieldsList);
		answer = TUI1.TestDoubleList();
		return (answer);
	}
	
	/**
	* @param args the command line arguments
	*/
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				CylinderDialog dialog = new CylinderDialog(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}
	
	public void FillFields(double d1, double d2, double d3, double d4, double d5, String s1) {
		length = d1;
		Diameter = d2;
		Mass = d3;
		Position = d4;
		Name = s1;
		RadialPosition = d5;
		
		CylLengthText.setText(Double.toString(length));
		CylODText.setText(Double.toString(Diameter));
		CylMassText.setText(Double.toString(Mass));
		CylPosText.setText(Double.toString(Position));
		CylNameText.setText(Name);
		CylRadPosText.setText(Double.toString(RadialPosition));
	}
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel CylDLable;
	private javax.swing.JLabel CylDUnit;
	private javax.swing.JLabel CylLengthLabel;
	private javax.swing.JTextField CylLengthText;
	private javax.swing.JLabel CylLengthUnit;
	private javax.swing.JLabel CylMassLabel;
	private javax.swing.JTextField CylMassText;
	private javax.swing.JLabel CylMassUnit;
	private javax.swing.JLabel CylNameLabel;
	private javax.swing.JTextField CylNameText;
	private javax.swing.JTextField CylODText;
	private javax.swing.JLabel CylPosLabel;
	private javax.swing.JTextField CylPosText;
	private javax.swing.JLabel CylPosUnit;
	private javax.swing.JLabel CylRadPosLabel;
	private javax.swing.JTextField CylRadPosText;
	private javax.swing.JLabel CylRadPosUnit;
	private javax.swing.JLabel CylSpecTitle;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	// End of variables declaration//GEN-END:variables
	
}
