/*
%## Copyright (C) 2011, 2016 S.Box
%## 
%## This program is free software; you can redistribute it and/or modify
%## it under the terms of the GNU General Public License as published by
%## the Free Software Foundation; either version 2 of the License, or
%## (at your option) any later version.
%## 
%## This program is distributed in the hope that it will be useful,
%## but WITHOUT ANY WARRANTY; without even the implied warranty of
%## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%## GNU General Public License for more details.
%## 
%## You should have received a copy of the GNU General Public License
%## along with this program; if not, write to the Free Software
%## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

%## Cylinder Dialog.java

%## Author: S.Box
%## Created: 2011-09-09

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DataTable.java
 *
 * Created on 09-Sep-2011, 17:38:59
 */

package net.sf.openrocket.camrocksim;

import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author simon
 */
public class DataTable extends javax.swing.JPanel {
	DefaultTableModel DTM = new DefaultTableModel();
	RWsimOutXML readsimDat;
	boolean DataLoaded;
	
	/** Creates new form DataTable */
	public DataTable() {
		initComponents();
		jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
		DataLoaded = false;
	}
	
	private void setStageCombo() {
		if (DataLoaded) {
			DefaultComboBoxModel CbM = new DefaultComboBoxModel();
			SimulationOutputData SoD1 = readsimDat.DataList.firstElement();
			SoD1.StageName = "Main Stage";
			CbM.addElement(SoD1);
			if (readsimDat.DataList.size() > 1) {
				SimulationOutputData SoD2 = readsimDat.DataList.elementAt(1);
				SoD2.StageName = "Booster_1";
				CbM.addElement(SoD2);
			}
			StageSelectorCombo.setModel(CbM);
		}
	}
	
	public void LoadDataFile(String FN) {
		readsimDat = new RWsimOutXML(FN);
		readsimDat.ReadXMLtoSimOdata();
		DataLoaded = true;
		setStageCombo();
	}
	
	public void MakeDataTable() {
		if (DataLoaded) {
			int iD = StageSelectorCombo.getSelectedIndex();
			DTM = readsimDat.DataList.elementAt(iD).toTable();
			jTable1.setModel(DTM);
			for (int i = 0; i < jTable1.getColumnCount(); i++) {
				jTable1.getColumnModel().getColumn(i).setPreferredWidth(100);
			}
		}
	}
	
	public void MakeSummaryData() {
		if (DataLoaded) {
			int iD = StageSelectorCombo.getSelectedIndex();
			String TextSum = readsimDat.DataList.elementAt(iD).SummaryData();
			jTextPane1.setText(TextSum);
		}
		
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextPane1 = new javax.swing.JTextPane();
		jPanel2 = new javax.swing.JPanel();
		StageSelectorCombo = new javax.swing.JComboBox();
		jLabel1 = new javax.swing.JLabel();
		StageLoader = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		
		jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				jTabbedPane1FocusGained(evt);
			}
		});
		
		jTextPane1.setEditable(false);
		jTextPane1.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				jTextPane1FocusGained(evt);
			}
		});
		jScrollPane2.setViewportView(jTextPane1);
		
		StageSelectorCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Main Stage" }));
		
		jLabel1.setText("Select Stage");
		
		StageLoader.setText("Load");
		StageLoader.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				StageLoaderActionPerformed(evt);
			}
		});
		
		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel1)
										.addGroup(jPanel2Layout.createSequentialGroup()
												.addComponent(StageSelectorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addComponent(StageLoader, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(41, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(StageSelectorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(StageLoader))
								.addContainerGap(30, Short.MAX_VALUE)));
		
		jButton1.setText("?");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		
		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGap(30, 30, 30)
								.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(jPanel1Layout.createSequentialGroup()
												.addGap(18, 18, 18)
												.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addContainerGap(68, Short.MAX_VALUE))
										.addGroup(jPanel1Layout.createSequentialGroup()
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addContainerGap()))));
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addContainerGap(14, Short.MAX_VALUE)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
												.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(22, 22, 22))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
												.addComponent(jButton1)
												.addContainerGap()))));
		
		jTabbedPane1.addTab("Data Summary", jPanel1);
		
		jTable1.setModel(DTM);
		jScrollPane1.setViewportView(jTable1);
		
		jTabbedPane1.addTab("DataTable", jScrollPane1);
		
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(21, Short.MAX_VALUE)));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(35, Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents
	
	private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
		// TODO add your handling code here:
	}//GEN-LAST:event_jTabbedPane1FocusGained
	
	private void jTextPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPane1FocusGained
	
	}//GEN-LAST:event_jTextPane1FocusGained
	
	private void StageLoaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StageLoaderActionPerformed
		if (!DataLoaded) {
			LoadDataFile("SimulationOutput.xml");
		}
		MakeSummaryData();
		MakeDataTable();
	}//GEN-LAST:event_StageLoaderActionPerformed
	
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		Tips tDiag = new Tips(null, true);
		tDiag.setTipTxt(
				"Data Tab \n\n Use this tab to view data from the last run simulation. A data summary appears in the pane on the  \"Data Summary\" tab and detailed flight data can be found under the \"Data Table\" tab. \n\n If a multi stage simulation was run you can use the combo box in the Data Summary tab to choose which stage you want to view data for. This changes the data displayed both in the summary pane and the data table. \n\n If a Monte Carlo simulation was run then the data displayed are for the mean flight only.");
		tDiag.setVisible(true);
	}//GEN-LAST:event_jButton1ActionPerformed
	
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton StageLoader;
	private javax.swing.JComboBox StageSelectorCombo;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextPane jTextPane1;
	// End of variables declaration//GEN-END:variables
	
}
