/*
%## Copyright (C) 2008, 2016 S.Box
%## 
%## This program is free software; you can redistribute it and/or modify
%## it under the terms of the GNU General Public License as published by
%## the Free Software Foundation; either version 2 of the License, or
%## (at your option) any later version.
%## 
%## This program is distributed in the hope that it will be useful,
%## but WITHOUT ANY WARRANTY; without even the implied warranty of
%## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%## GNU General Public License for more details.
%## 
%## You should have received a copy of the GNU General Public License
%## along with this program; if not, write to the Free Software
%## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

%## ascent_variables.m

%## Author: S.Box
%## Created: 2010-05-27
/*
 * BodyTubeDialog.java
 *
 * Created on 29 April 2009, 13:41
 */

package net.sf.openrocket.camrocksim;

import java.util.Vector;

import javax.swing.JOptionPane;

/**
 *
 * @author  sb4p07
 */
public class FinsetDialog extends javax.swing.JDialog {
	
	//**Class Members
	int FinNum;
	double RootChord,
			TipChord,
			Span,
			Sweep,
			BodyDiam,
			Thickness,
			Mass,
			Position;
	boolean ReadOk;
	String Name;
	
	/** Creates new form BodyTubeDialog */
	public FinsetDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		
		FinsetSpecTitle = new javax.swing.JLabel();
		FinsetNameLabel = new javax.swing.JLabel();
		FinsetFinNumLabel = new javax.swing.JLabel();
		FinsetRCLabel = new javax.swing.JLabel();
		FinsetTCLabel = new javax.swing.JLabel();
		FinsetSpanLable = new javax.swing.JLabel();
		FinsetSweepLabel = new javax.swing.JLabel();
		FinsetBDLabel = new javax.swing.JLabel();
		FinsetThickLabel = new javax.swing.JLabel();
		FinsetMassLabel = new javax.swing.JLabel();
		FinsetPosLabel = new javax.swing.JLabel();
		FinsetNameText = new javax.swing.JTextField();
		FinsetFinNumComboBox = new javax.swing.JComboBox();
		FinsetRCText = new javax.swing.JTextField();
		FinsetTCText = new javax.swing.JTextField();
		FinsetSpanText = new javax.swing.JTextField();
		FinsetSweepText = new javax.swing.JTextField();
		FinsetBDText = new javax.swing.JTextField();
		FinsetThickText = new javax.swing.JTextField();
		FinsetMassText = new javax.swing.JTextField();
		FinsetPosText = new javax.swing.JTextField();
		FinsetRCUnit = new javax.swing.JLabel();
		FinsetTCUnit = new javax.swing.JLabel();
		FinsetSpanUnit = new javax.swing.JLabel();
		FinsetBDUnit = new javax.swing.JLabel();
		FinsetThickUnit = new javax.swing.JLabel();
		FinsetMassUnit = new javax.swing.JLabel();
		FinsetPosUnit = new javax.swing.JLabel();
		FinsetSweepUnit = new javax.swing.JLabel();
		FinsetAddButton = new javax.swing.JButton();
		FinsetCancelButton = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();
		
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		
		FinsetSpecTitle.setText("Set finset specifications");
		
		FinsetNameLabel.setText("Name");
		
		FinsetFinNumLabel.setText("Number of Fins");
		
		FinsetRCLabel.setText("Root Chord");
		
		FinsetTCLabel.setText("Tip Chord");
		
		FinsetSpanLable.setText("Span");
		
		FinsetSweepLabel.setText("Sweep");
		
		FinsetBDLabel.setText("Body Diameter At Fins");
		
		FinsetThickLabel.setText("Thickness");
		
		FinsetMassLabel.setText("Mass");
		
		FinsetPosLabel.setText("Position");
		
		FinsetNameText.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				FinsetNameTextFocusLost(evt);
			}
		});
		
		FinsetFinNumComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "4" }));
		
		FinsetRCText.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				FinsetRCTextFocusLost(evt);
			}
		});
		
		FinsetTCText.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				FinsetTCTextFocusLost(evt);
			}
		});
		
		FinsetSpanText.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				FinsetSpanTextActionPerformed(evt);
			}
		});
		FinsetSpanText.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				FinsetSpanTextFocusLost(evt);
			}
		});
		
		FinsetSweepText.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				FinsetSweepTextFocusLost(evt);
			}
		});
		
		FinsetBDText.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				FinsetBDTextFocusLost(evt);
			}
		});
		
		FinsetThickText.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				FinsetThickTextFocusLost(evt);
			}
		});
		
		FinsetMassText.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				FinsetMassTextFocusLost(evt);
			}
		});
		
		FinsetPosText.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				FinsetPosTextFocusLost(evt);
			}
		});
		
		FinsetRCUnit.setText("m");
		
		FinsetTCUnit.setText("m");
		
		FinsetSpanUnit.setText("m");
		
		FinsetBDUnit.setText("m");
		
		FinsetThickUnit.setText("m");
		
		FinsetMassUnit.setText("kg");
		
		FinsetPosUnit.setText("m");
		
		FinsetSweepUnit.setText("m");
		
		FinsetAddButton.setText("Add");
		FinsetAddButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				FinsetAddButtonActionPerformed(evt);
			}
		});
		
		FinsetCancelButton.setText("Cancel");
		FinsetCancelButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				FinsetCancelButtonActionPerformed(evt);
			}
		});
		
		jButton1.setText("?");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addContainerGap()
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(FinsetSpecTitle)
														.addGroup(layout.createSequentialGroup()
																.addGap(10, 10, 10)
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(FinsetRCLabel)
																		.addComponent(FinsetFinNumLabel)
																		.addComponent(FinsetTCLabel)
																		.addComponent(FinsetSpanLable)
																		.addComponent(FinsetSweepLabel)
																		.addComponent(FinsetBDLabel)
																		.addComponent(FinsetThickLabel)
																		.addComponent(FinsetMassLabel)
																		.addComponent(FinsetPosLabel)
																		.addComponent(FinsetNameLabel))
																.addGap(47, 47, 47)
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
																				.addComponent(FinsetPosText, javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(FinsetMassText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134,
																						Short.MAX_VALUE)
																				.addComponent(FinsetFinNumComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(FinsetTCText, javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(FinsetSpanText, javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(FinsetSweepText, javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(FinsetBDText, javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(FinsetRCText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135,
																						Short.MAX_VALUE)
																				.addComponent(FinsetThickText, javax.swing.GroupLayout.Alignment.LEADING))
																		.addComponent(FinsetNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(FinsetRCUnit, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
																		.addComponent(FinsetTCUnit, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
																		.addComponent(FinsetSpanUnit, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
																		.addComponent(FinsetBDUnit, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
																		.addComponent(FinsetSweepUnit, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
																		.addComponent(FinsetThickUnit, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
																		.addComponent(FinsetMassUnit, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
																		.addComponent(FinsetPosUnit, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))))
										.addGroup(layout.createSequentialGroup()
												.addGap(115, 115, 115)
												.addComponent(FinsetAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addComponent(FinsetCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap()));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(FinsetSpecTitle)
								.addGap(36, 36, 36)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(FinsetNameLabel)
										.addComponent(FinsetNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(FinsetFinNumComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(FinsetFinNumLabel))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(FinsetRCText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(FinsetRCLabel)
										.addComponent(FinsetRCUnit))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(FinsetTCText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(FinsetTCLabel)
										.addComponent(FinsetTCUnit))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(FinsetSpanText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(FinsetSpanLable)
										.addComponent(FinsetSpanUnit))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(FinsetSweepText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(FinsetSweepLabel)
										.addComponent(FinsetSweepUnit))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(FinsetBDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(FinsetBDLabel)
										.addComponent(FinsetBDUnit))
								.addGap(10, 10, 10)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(FinsetThickText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(FinsetThickLabel)
										.addComponent(FinsetThickUnit))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(FinsetMassText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(FinsetMassLabel)
										.addComponent(FinsetMassUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(FinsetPosText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(FinsetPosLabel)
										.addComponent(FinsetPosUnit))
								.addGap(86, 86, 86)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(FinsetAddButton)
										.addComponent(FinsetCancelButton)
										.addComponent(jButton1))
								.addGap(54, 54, 54)));
		
		pack();
	}// </editor-fold>//GEN-END:initComponents
	
	private void FinsetRCTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FinsetRCTextFocusLost
		//Function to test the validity of the user input
		TestUserTextInput RCTest = new TestUserTextInput(FinsetRCText);
		RootChord = RCTest.TestDouble();
		FinsetRCText = RCTest.InputField;
	}//GEN-LAST:event_FinsetRCTextFocusLost
	
	private void FinsetTCTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FinsetTCTextFocusLost
		///Function to test the validity of the user input
		TestUserTextInput TCTest = new TestUserTextInput(FinsetTCText);
		TipChord = TCTest.TestDouble();
		FinsetTCText = TCTest.InputField;
	}//GEN-LAST:event_FinsetTCTextFocusLost
	
	private void FinsetSpanTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FinsetSpanTextFocusLost
		///Function to test the validity of the user input
		TestUserTextInput SpanTest = new TestUserTextInput(FinsetSpanText);
		Span = SpanTest.TestDouble();
		FinsetSpanText = SpanTest.InputField;
	}//GEN-LAST:event_FinsetSpanTextFocusLost
	
	private void FinsetSweepTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FinsetSweepTextFocusLost
		///Function to test the validity of the user input
		TestUserTextInput MCTest = new TestUserTextInput(FinsetSweepText);
		Sweep = MCTest.TestDouble();
		FinsetSweepText = MCTest.InputField;
	}//GEN-LAST:event_FinsetSweepTextFocusLost
	
	private void FinsetMassTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FinsetMassTextFocusLost
		///Function to test the validity of the user input
		TestUserTextInput MassTest = new TestUserTextInput(FinsetMassText);
		Mass = MassTest.TestDouble();
		FinsetMassText = MassTest.InputField;
	}//GEN-LAST:event_FinsetMassTextFocusLost
	
	private void FinsetNameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FinsetNameTextFocusLost
		// TODO add your handling code here:
		Name = FinsetNameText.getText();
	}//GEN-LAST:event_FinsetNameTextFocusLost
	
	private void FinsetCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinsetCancelButtonActionPerformed
		// TODO add your handling code here:
		this.dispose();
	}//GEN-LAST:event_FinsetCancelButtonActionPerformed
	
	private void FinsetAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinsetAddButtonActionPerformed
		// TODO add your handling code here:
		boolean Goer = CheckValidity();
		if (Goer == true) {
			switch (FinsetFinNumComboBox.getSelectedIndex()) {
			case 0:
				FinNum = 3;
				break;
			case 1:
				FinNum = 4;
				break;
			}
			ReadOk = true;
			this.dispose();
		} else {
			JOptionPane.showMessageDialog(null, ("Something is wrong with the data that you entered"));
			;
		}
	}//GEN-LAST:event_FinsetAddButtonActionPerformed
	
	private void FinsetPosTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FinsetPosTextFocusLost
		//Function to test the validity of the user input
		TestUserTextInput PosTest = new TestUserTextInput(FinsetPosText);
		Position = PosTest.TestDouble();
		FinsetPosText = PosTest.InputField;
	}//GEN-LAST:event_FinsetPosTextFocusLost
	
	private void FinsetBDTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FinsetBDTextFocusLost
		//Function to test the validity of the user input
		TestUserTextInput BDTest = new TestUserTextInput(FinsetBDText);
		BodyDiam = BDTest.TestDouble();
		FinsetBDText = BDTest.InputField;
	}//GEN-LAST:event_FinsetBDTextFocusLost
	
	private void FinsetThickTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FinsetThickTextFocusLost
		//Function to test the validity of the user input
		TestUserTextInput ThickTest = new TestUserTextInput(FinsetThickText);
		Thickness = ThickTest.TestDouble();
		FinsetThickText = ThickTest.InputField;
	}//GEN-LAST:event_FinsetThickTextFocusLost
	
	private void FinsetSpanTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinsetSpanTextActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_FinsetSpanTextActionPerformed
	
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		Tips tDiag = new Tips(null, true);
		tDiag.setTipTxt(
				"Fin set Settings \n\n Use this window to specify the parameters of the Fin set. Position is the distance, along the rocket's axis, from the nose tip to the foremost edge of the part.");
		tDiag.setVisible(true);
	}//GEN-LAST:event_jButton1ActionPerformed
	
	private boolean CheckValidity() {
		boolean answer;
		Vector<javax.swing.JTextField> FieldsList = new Vector<javax.swing.JTextField>();
		FieldsList.add(FinsetRCText);
		FieldsList.add(FinsetTCText);
		FieldsList.add(FinsetSpanText);
		FieldsList.add(FinsetSweepText);
		FieldsList.add(FinsetBDText);
		FieldsList.add(FinsetThickText);
		FieldsList.add(FinsetMassText);
		FieldsList.add(FinsetPosText);
		
		TestUserTextInput TUI1 = new TestUserTextInput(FieldsList);
		answer = TUI1.TestDoubleList();
		return (answer);
	}
	
	/**
	* @param args the command line arguments
	*/
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				FinsetDialog dialog = new FinsetDialog(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}
	
	public void FillFields(int i1, double d1, double d2, double d4, double d5, double d6, double d7, double d9, double d10, String s1) {
		FinNum = i1;
		RootChord = d1;
		TipChord = d2;
		Span = d4;
		Sweep = d5;
		Thickness = d6;
		BodyDiam = d7;
		Mass = d9;
		Position = d10;
		Name = s1;
		
		FinsetFinNumComboBox.setSelectedIndex((FinNum - 3));
		FinsetRCText.setText(Double.toString(RootChord));
		FinsetTCText.setText(Double.toString(TipChord));
		FinsetSpanText.setText(Double.toString(Span));
		FinsetSweepText.setText(Double.toString(Sweep));
		FinsetThickText.setText(Double.toString(Thickness));
		FinsetBDText.setText(Double.toString(BodyDiam));
		FinsetMassText.setText(Double.toString(Mass));
		FinsetPosText.setText(Double.toString(Position));
		FinsetNameText.setText(Name);
		
		
	}
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton FinsetAddButton;
	private javax.swing.JLabel FinsetBDLabel;
	private javax.swing.JTextField FinsetBDText;
	private javax.swing.JLabel FinsetBDUnit;
	private javax.swing.JButton FinsetCancelButton;
	private javax.swing.JComboBox FinsetFinNumComboBox;
	private javax.swing.JLabel FinsetFinNumLabel;
	private javax.swing.JLabel FinsetMassLabel;
	private javax.swing.JTextField FinsetMassText;
	private javax.swing.JLabel FinsetMassUnit;
	private javax.swing.JLabel FinsetNameLabel;
	private javax.swing.JTextField FinsetNameText;
	private javax.swing.JLabel FinsetPosLabel;
	private javax.swing.JTextField FinsetPosText;
	private javax.swing.JLabel FinsetPosUnit;
	private javax.swing.JLabel FinsetRCLabel;
	private javax.swing.JTextField FinsetRCText;
	private javax.swing.JLabel FinsetRCUnit;
	private javax.swing.JLabel FinsetSpanLable;
	private javax.swing.JTextField FinsetSpanText;
	private javax.swing.JLabel FinsetSpanUnit;
	private javax.swing.JLabel FinsetSpecTitle;
	private javax.swing.JLabel FinsetSweepLabel;
	private javax.swing.JTextField FinsetSweepText;
	private javax.swing.JLabel FinsetSweepUnit;
	private javax.swing.JLabel FinsetTCLabel;
	private javax.swing.JTextField FinsetTCText;
	private javax.swing.JLabel FinsetTCUnit;
	private javax.swing.JLabel FinsetThickLabel;
	private javax.swing.JTextField FinsetThickText;
	private javax.swing.JLabel FinsetThickUnit;
	private javax.swing.JButton jButton1;
	// End of variables declaration//GEN-END:variables
	
}
