/*
%## Copyright (C) 2010, 2016 S.Box
%## 
%## This program is free software; you can redistribute it and/or modify
%## it under the terms of the GNU General Public License as published by
%## the Free Software Foundation; either version 2 of the License, or
%## (at your option) any later version.
%## 
%## This program is distributed in the hope that it will be useful,
%## but WITHOUT ANY WARRANTY; without even the implied warranty of
%## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%## GNU General Public License for more details.
%## 
%## You should have received a copy of the GNU General Public License
%## along with this program; if not, write to the Free Software
%## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

%## MainForm.java

%## Author: S.Box
%## Created: 2010-05-27
/*
 * MainForm.java
 *
 * Created on 16 April 2009, 21:00
 */

package net.sf.openrocket.camrocksim;


import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author  simon
 */
public class MainForm extends javax.swing.JFrame {
	
	//*Class Members
	private RocketDescription TheRocket = new RocketDescription();
	int LastTreeRow;
	private ProfilePreLoader PPL;
	public MotorsList TheMotors;
	private AtmosphereList Atmospheres;
	private AtmosphereData TheAtmosphere = new AtmosphereData();
	private LaunchData LaunchPadSet = new LaunchData();
	
	
	/** Creates new form MainForm */
	public MainForm() {
		PPL = new ProfilePreLoader();
		TheMotors = PPL.getMotors();
		Atmospheres = PPL.getAmospheres();
		
		initComponents();
		UpdateTree();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		
		TreeRightClickMenu = new javax.swing.JPopupMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem2 = new javax.swing.JMenuItem();
		ListRightClickMenu = new javax.swing.JPopupMenu();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenuItem4 = new javax.swing.JMenuItem();
		AtmosListMenu = new javax.swing.JPopupMenu();
		EditAtmos = new javax.swing.JMenuItem();
		AtmosDelete = new javax.swing.JMenuItem();
		jPanel3 = new javax.swing.JPanel();
		jTabbedPane2 = new javax.swing.JTabbedPane();
		MotorDesignPanel = new javax.swing.JPanel();
		jPanel7 = new javax.swing.JPanel();
		MotorCreationButton = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jScrollPane4 = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList();
		jLabel12 = new javax.swing.JLabel();
		MotorPaneTips = new javax.swing.JButton();
		RocketDesignPanel = new javax.swing.JPanel();
		jPanel6 = new javax.swing.JPanel();
		DesignLoadButton = new javax.swing.JButton();
		PartSelectFrameTitle = new javax.swing.JLabel();
		WriteToFileButton = new javax.swing.JButton();
		jLabel11 = new javax.swing.JLabel();
		jPanel8 = new javax.swing.JPanel();
		AddBodyLabel = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jButton1 = new javax.swing.JButton();
		MassPartChoose = new javax.swing.JComboBox();
		MassPartSet = new javax.swing.JButton();
		AddMassLabel = new javax.swing.JLabel();
		BodyPartChoose = new javax.swing.JComboBox();
		BodyPartSet = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		StageComboBox = new javax.swing.JComboBox();
		BoosterStageButton = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		AtmospherePanel = new javax.swing.JPanel();
		jPanel5 = new javax.swing.JPanel();
		jScrollPane3 = new javax.swing.JScrollPane();
		jList2 = new javax.swing.JList();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		jButton8 = new javax.swing.JButton();
		SimulationPanel = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		AtmosphereComboBox = new javax.swing.JComboBox();
		jLabel6 = new javax.swing.JLabel();
		DeclinationField = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		LaunchRailField = new javax.swing.JTextField();
		MonteCarloField = new javax.swing.JTextField();
		MonteCarloRadio = new javax.swing.JRadioButton();
		jLabel8 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		AzimuthField = new javax.swing.JTextField();
		ConfigSaveButton = new javax.swing.JButton();
		jButton9 = new javax.swing.JButton();
		PlotterPanel = new javax.swing.JPanel();
		dataTable1 = new net.sf.openrocket.camrocksim.DataTable();
		jPanel9 = new javax.swing.JPanel();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTree1 = new javax.swing.JTree();
		EditPartButton = new javax.swing.JButton();
		DeletePartButton = new javax.swing.JButton();
		
		jMenuItem1.setText("Edit");
		jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jMenuItem1MouseReleased(evt);
			}
		});
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		TreeRightClickMenu.add(jMenuItem1);
		
		jMenuItem2.setText("Delete");
		jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jMenuItem2MouseReleased(evt);
			}
		});
		jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem2ActionPerformed(evt);
			}
		});
		TreeRightClickMenu.add(jMenuItem2);
		
		jMenuItem3.setText("Edit");
		jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem3ActionPerformed(evt);
			}
		});
		ListRightClickMenu.add(jMenuItem3);
		
		jMenuItem4.setText("Delete");
		jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem4ActionPerformed(evt);
			}
		});
		ListRightClickMenu.add(jMenuItem4);
		
		EditAtmos.setText("Edit");
		EditAtmos.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				EditAtmosActionPerformed(evt);
			}
		});
		AtmosListMenu.add(EditAtmos);
		
		AtmosDelete.setText("Delete");
		AtmosDelete.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				AtmosDeleteActionPerformed(evt);
			}
		});
		AtmosListMenu.add(AtmosDelete);
		
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Cambridge Rocketry Simulator -- version 2.3(beta)");
		setBounds(new java.awt.Rectangle(0, 0, 20, 0));
		
		jTabbedPane2.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				jTabbedPane2FocusGained(evt);
			}
		});
		
		jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		
		MotorCreationButton.setText("Create New Motor");
		MotorCreationButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				MotorCreationButtonMouseReleased(evt);
			}
		});
		MotorCreationButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				MotorCreationButtonActionPerformed(evt);
			}
		});
		
		jButton3.setText("Load Motor");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		
		jButton2.setText("Edit Selected Motor");
		jButton2.setEnabled(false);
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		
		jList1.setModel(TheMotors.MotListMod);
		jList1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jList1MousePressed(evt);
			}
			
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jList1MouseReleased(evt);
			}
		});
		jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
			public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
				jList1ValueChanged(evt);
			}
		});
		jList1.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				jList1FocusGained(evt);
			}
			
			public void focusLost(java.awt.event.FocusEvent evt) {
				jList1FocusLost(evt);
			}
		});
		jScrollPane4.setViewportView(jList1);
		
		jLabel12.setText("Loaded Motors");
		
		MotorPaneTips.setText("?");
		MotorPaneTips.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				MotorPaneTipsActionPerformed(evt);
			}
		});
		
		javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout.setHorizontalGroup(
				jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel7Layout.createSequentialGroup()
								.addGap(150, 150, 150)
								.addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
										.addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel12))
								.addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(jPanel7Layout.createSequentialGroup()
												.addGap(124, 124, 124)
												.addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
														.addComponent(MotorCreationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jButton2))
												.addContainerGap(188, Short.MAX_VALUE))
										.addGroup(jPanel7Layout.createSequentialGroup()
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(MotorPaneTips, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addContainerGap()))));
		jPanel7Layout.setVerticalGroup(
				jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel12)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(30, 30, 30))
						.addGroup(jPanel7Layout.createSequentialGroup()
								.addGap(83, 83, 83)
								.addComponent(jButton3)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jButton2)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(MotorCreationButton)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
								.addComponent(MotorPaneTips)
								.addContainerGap()));
		
		javax.swing.GroupLayout MotorDesignPanelLayout = new javax.swing.GroupLayout(MotorDesignPanel);
		MotorDesignPanel.setLayout(MotorDesignPanelLayout);
		MotorDesignPanelLayout.setHorizontalGroup(
				MotorDesignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(MotorDesignPanelLayout.createSequentialGroup()
								.addGap(49, 49, 49)
								.addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(35, Short.MAX_VALUE)));
		MotorDesignPanelLayout.setVerticalGroup(
				MotorDesignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(MotorDesignPanelLayout.createSequentialGroup()
								.addGap(38, 38, 38)
								.addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(141, Short.MAX_VALUE)));
		
		jTabbedPane2.addTab("Motor Design", MotorDesignPanel);
		
		jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		
		DesignLoadButton.setText("Load Design");
		DesignLoadButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DesignLoadButtonActionPerformed(evt);
			}
		});
		
		PartSelectFrameTitle.setText("Add Rocket Components");
		
		WriteToFileButton.setText("Save Design");
		WriteToFileButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				WriteToFileButtonActionPerformed(evt);
			}
		});
		
		jLabel11.setText("Load/Save Designs");
		
		jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		
		AddBodyLabel.setText("Add Body Part");
		
		jComboBox1.setModel(TheMotors.MotListCombo);
		jComboBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox1ActionPerformed(evt);
			}
		});
		
		jButton1.setText("Add");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		
		MassPartChoose.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cylinder", "Tube", "Block", "Cone Section", "Point Mass", "Parachute" }));
		MassPartChoose.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				MassPartChooseActionPerformed(evt);
			}
		});
		
		MassPartSet.setText("Add");
		MassPartSet.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				MassPartSetActionPerformed(evt);
			}
		});
		
		AddMassLabel.setText("Add Internal Part");
		
		BodyPartChoose.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nose Cone", "Body Tube", "Conic Transition", "Fin Set" }));
		
		BodyPartSet.setText("Add");
		BodyPartSet.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BodyPartSetActionPerformed(evt);
			}
		});
		
		jLabel1.setText("Add Motor");
		
		jLabel13.setText("Add Part To:");
		
		StageComboBox.setModel(TheRocket.StageCombo);
		
		BoosterStageButton.setText("Add Booster Stage");
		BoosterStageButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BoosterStageButtonActionPerformed(evt);
			}
		});
		
		javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
		jPanel8.setLayout(jPanel8Layout);
		jPanel8Layout.setHorizontalGroup(
				jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel8Layout.createSequentialGroup()
								.addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
												.addGap(166, 166, 166)
												.addComponent(BoosterStageButton))
										.addGroup(jPanel8Layout.createSequentialGroup()
												.addContainerGap()
												.addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel13)
														.addComponent(AddBodyLabel)
														.addComponent(AddMassLabel)
														.addComponent(jLabel1))
												.addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(jPanel8Layout.createSequentialGroup()
																.addGap(12, 12, 12)
																.addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
																		.addComponent(BodyPartChoose, 0, 171, Short.MAX_VALUE)
																		.addComponent(MassPartChoose, 0, 171, Short.MAX_VALUE)
																		.addComponent(jComboBox1, 0, 171, Short.MAX_VALUE))
																.addGap(18, 18, 18)
																.addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																		.addComponent(MassPartSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																		.addComponent(BodyPartSet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
														.addGroup(jPanel8Layout.createSequentialGroup()
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(StageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))))
								.addContainerGap()));
		jPanel8Layout.setVerticalGroup(
				jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
								.addGap(30, 30, 30)
								.addComponent(BoosterStageButton)
								.addGap(29, 29, 29)
								.addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel13)
										.addComponent(StageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(39, 39, 39)
								.addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(BodyPartChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE)
										.addComponent(AddBodyLabel)
										.addComponent(BodyPartSet, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(MassPartChoose, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
										.addComponent(AddMassLabel)
										.addComponent(MassPartSet, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jComboBox1)
										.addComponent(jLabel1)
										.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(40, 40, 40)));
		
		jButton4.setText("?");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});
		
		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(
				jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel6Layout.createSequentialGroup()
								.addGap(46, 46, 46)
								.addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGap(130, 130, 130)
								.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
										.addComponent(jLabel11)
										.addComponent(DesignLoadButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
										.addComponent(WriteToFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
								.addGap(99, 99, 99))
						.addGroup(jPanel6Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(PartSelectFrameTitle)
								.addContainerGap(606, Short.MAX_VALUE))
						.addGroup(jPanel6Layout.createSequentialGroup()
								.addGap(746, 746, 746)
								.addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));
		jPanel6Layout.setVerticalGroup(
				jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel6Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(PartSelectFrameTitle)
								.addGap(68, 68, 68)
								.addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(59, 59, 59))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
								.addContainerGap(122, Short.MAX_VALUE)
								.addComponent(jLabel11)
								.addGap(42, 42, 42)
								.addComponent(DesignLoadButton)
								.addGap(40, 40, 40)
								.addComponent(WriteToFileButton)
								.addGap(128, 128, 128)
								.addComponent(jButton4)
								.addContainerGap()));
		
		javax.swing.GroupLayout RocketDesignPanelLayout = new javax.swing.GroupLayout(RocketDesignPanel);
		RocketDesignPanel.setLayout(RocketDesignPanelLayout);
		RocketDesignPanelLayout.setHorizontalGroup(
				RocketDesignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(RocketDesignPanelLayout.createSequentialGroup()
								.addGap(33, 33, 33)
								.addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(25, Short.MAX_VALUE)));
		RocketDesignPanelLayout.setVerticalGroup(
				RocketDesignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(RocketDesignPanelLayout.createSequentialGroup()
								.addGap(21, 21, 21)
								.addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(13, Short.MAX_VALUE)));
		
		jTabbedPane2.addTab("Rocket Design", RocketDesignPanel);
		RocketDesignPanel.getAccessibleContext().setAccessibleParent(RocketDesignPanel);
		
		jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		
		jList2.setModel(Atmospheres.AtmosListMod);
		jList2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jList2MousePressed(evt);
			}
		});
		jScrollPane3.setViewportView(jList2);
		
		jButton6.setText("Edit Selected Profile");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});
		
		jButton7.setText("Load Profile");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});
		
		jButton5.setText("Create New Profile");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});
		
		jLabel4.setText("Loaded Wind Profiles");
		
		jButton8.setText("?");
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});
		
		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(
				jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel5Layout.createSequentialGroup()
								.addGap(184, 184, 184)
								.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
										.addComponent(jLabel4)
										.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(88, 88, 88)
								.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
										.addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
								.addGap(210, 210, 210))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
								.addContainerGap(734, Short.MAX_VALUE)
								.addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));
		jPanel5Layout.setVerticalGroup(
				jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel5Layout.createSequentialGroup()
								.addGap(53, 53, 53)
								.addComponent(jLabel4)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel5Layout.createSequentialGroup()
												.addComponent(jButton7)
												.addGap(18, 18, 18)
												.addComponent(jButton6)
												.addGap(18, 18, 18)
												.addComponent(jButton5))
										.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
								.addComponent(jButton8)
								.addContainerGap()));
		
		javax.swing.GroupLayout AtmospherePanelLayout = new javax.swing.GroupLayout(AtmospherePanel);
		AtmospherePanel.setLayout(AtmospherePanelLayout);
		AtmospherePanelLayout.setHorizontalGroup(
				AtmospherePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(AtmospherePanelLayout.createSequentialGroup()
								.addGap(43, 43, 43)
								.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(24, Short.MAX_VALUE)));
		AtmospherePanelLayout.setVerticalGroup(
				AtmospherePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(AtmospherePanelLayout.createSequentialGroup()
								.addGap(30, 30, 30)
								.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(88, Short.MAX_VALUE)));
		
		jTabbedPane2.addTab("Wind Conditions", AtmospherePanel);
		
		jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		
		jLabel3.setText("degs");
		
		jLabel9.setText("Set Declination Angle");
		
		jLabel7.setText("Set Launch Rail Lenth");
		
		jLabel10.setText("Number of runs");
		
		AtmosphereComboBox.setModel(Atmospheres.AtmosListCombo);
		AtmosphereComboBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				AtmosphereComboBoxActionPerformed(evt);
			}
		});
		
		jLabel6.setText("Choose Wind Profile");
		
		DeclinationField.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				DeclinationFieldFocusLost(evt);
			}
		});
		
		jLabel5.setText("degs");
		
		LaunchRailField.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				LaunchRailFieldFocusLost(evt);
			}
		});
		
		MonteCarloField.setEnabled(false);
		
		MonteCarloRadio.setText("Use Monte Carlo");
		MonteCarloRadio.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				MonteCarloRadioActionPerformed(evt);
			}
		});
		
		jLabel8.setText("Set Azimuth Angle");
		
		jLabel2.setText("m");
		
		AzimuthField.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				AzimuthFieldFocusLost(evt);
			}
		});
		
		ConfigSaveButton.setText("LAUNCH");
		ConfigSaveButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ConfigSaveButtonActionPerformed(evt);
			}
		});
		
		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jLabel7)
										.addComponent(jLabel6)
										.addComponent(jLabel8)
										.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(MonteCarloRadio)
												.addComponent(jLabel9)))
								.addGap(34, 34, 34)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel2Layout.createSequentialGroup()
												.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
														.addComponent(DeclinationField, javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(AzimuthField, javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(LaunchRailField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel5)
														.addComponent(jLabel3)
														.addComponent(jLabel2))
												.addGap(127, 127, 127)
												.addComponent(ConfigSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(AtmosphereComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(jPanel2Layout.createSequentialGroup()
												.addComponent(MonteCarloField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jLabel10)))
								.addContainerGap()));
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel2Layout.createSequentialGroup()
												.addContainerGap()
												.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(AtmosphereComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel6))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(LaunchRailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel2)
														.addComponent(jLabel7))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(AzimuthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel3)
														.addComponent(jLabel8))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(DeclinationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel5)
														.addComponent(jLabel9))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(MonteCarloRadio)
														.addComponent(MonteCarloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel10)))
										.addGroup(jPanel2Layout.createSequentialGroup()
												.addGap(45, 45, 45)
												.addComponent(ConfigSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(62, Short.MAX_VALUE)));
		
		jButton9.setText("?");
		jButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton9ActionPerformed(evt);
			}
		});
		
		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(
				jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 658, Short.MAX_VALUE)
								.addGap(18, 18, 18)
								.addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(20, 20, 20)));
		jPanel4Layout.setVerticalGroup(
				jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel4Layout.createSequentialGroup()
								.addGap(30, 30, 30)
								.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGap(33, 33, 33))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
								.addContainerGap(283, Short.MAX_VALUE)
								.addComponent(jButton9)
								.addContainerGap()));
		
		javax.swing.GroupLayout SimulationPanelLayout = new javax.swing.GroupLayout(SimulationPanel);
		SimulationPanel.setLayout(SimulationPanelLayout);
		SimulationPanelLayout.setHorizontalGroup(
				SimulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(SimulationPanelLayout.createSequentialGroup()
								.addGap(67, 67, 67)
								.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(39, Short.MAX_VALUE)));
		SimulationPanelLayout.setVerticalGroup(
				SimulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(SimulationPanelLayout.createSequentialGroup()
								.addGap(32, 32, 32)
								.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(129, Short.MAX_VALUE)));
		
		jTabbedPane2.addTab("Launcher", SimulationPanel);
		
		javax.swing.GroupLayout PlotterPanelLayout = new javax.swing.GroupLayout(PlotterPanel);
		PlotterPanel.setLayout(PlotterPanelLayout);
		PlotterPanelLayout.setHorizontalGroup(
				PlotterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(PlotterPanelLayout.createSequentialGroup()
								.addContainerGap()
								.addComponent(dataTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		PlotterPanelLayout.setVerticalGroup(
				PlotterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(dataTable1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE));
		
		jTabbedPane2.addTab("Data Viewer", PlotterPanel);
		
		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel3Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(32, Short.MAX_VALUE)));
		jPanel3Layout.setVerticalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel3Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		
		jTabbedPane2.getAccessibleContext().setAccessibleName("Main Tabs");
		
		jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				jPanel1FocusLost(evt);
			}
		});
		
		jTree1.setModel(TheRocket.RocketTree);
		jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jTree1MousePressed(evt);
			}
			
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jTree1MouseReleased(evt);
			}
			
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTree1MouseClicked(evt);
			}
		});
		jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
			public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
				LeafIsSelected(evt);
			}
		});
		jTree1.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				jTree1FocusLost(evt);
			}
		});
		jScrollPane1.setViewportView(jTree1);
		
		EditPartButton.setText("Edit part");
		EditPartButton.setEnabled(false);
		EditPartButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				EditPartButtonActionPerformed(evt);
			}
		});
		
		DeletePartButton.setText("Delete Part");
		DeletePartButton.setEnabled(false);
		DeletePartButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DeletePartButtonActionPerformed(evt);
			}
		});
		
		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(jPanel1Layout.createSequentialGroup()
												.addComponent(EditPartButton)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(DeletePartButton)))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(EditPartButton)
										.addComponent(DeletePartButton))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		
		jTabbedPane1.addTab("The Rocket", jPanel1);
		
		javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
		jPanel9.setLayout(jPanel9Layout);
		jPanel9Layout.setHorizontalGroup(
				jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel9Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));
		jPanel9Layout.setVerticalGroup(
				jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
								.addContainerGap()));
		
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(8, 8, 8)
								.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(21, Short.MAX_VALUE)));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addContainerGap(65, Short.MAX_VALUE)));
		
		pack();
	}// </editor-fold>//GEN-END:initComponents
	
	private void BodyPartSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BodyPartSetActionPerformed
		// When Specs button is pressed launch a new specs window
		switch (BodyPartChoose.getSelectedIndex()) {
		case 0:
			NoseConeData Ndat = new NoseConeData();
			if (Ndat.built == true) {
				BodyAdder(Ndat);
				
			}
			break;
		case 1:
			BodyTubeData BTdat = new BodyTubeData();
			if (BTdat.built == true) {
				BodyAdder(BTdat);
				
			}
			break;
		case 2:
			ConicTransData CTdat = new ConicTransData();
			if (CTdat.built == true) {
				BodyAdder(CTdat);
				
			}
			break;
		case 3:
			FinsetData FSdata = new FinsetData();
			if (FSdata.built == true) {
				BodyAdder(FSdata);
				
			}
			break;
		default:
			jLabel4.setText("Error!");
			break;
		}
		
		/*int i = jComboBox1.getSelectedIndex();
		jLabel4.setText(("Index is: " + i));*/
	}//GEN-LAST:event_BodyPartSetActionPerformed
	
	private void BodyAdder(RockPartsData part) {
		TheRocket.addBodyPart(part, StageComboBox.getSelectedIndex());
		UpdateTree();
	}
	
	private void MassPartSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MassPartSetActionPerformed
		// When specs button is pressed launch new specs window
		switch (MassPartChoose.getSelectedIndex()) {
		case 0:
			CylinderData Cydat = new CylinderData();
			if (Cydat.built == true) {
				MassAdder(Cydat);
				
			}
			break;
		case 1:
			TubeData Tdat = new TubeData();
			if (Tdat.built == true) {
				MassAdder(Tdat);
				
			}
			break;
		case 2:
			BlockData Bdat = new BlockData();
			if (Bdat.built == true) {
				MassAdder(Bdat);
				
			}
			break;
		case 3:
			ConeSecData Cdat = new ConeSecData();
			if (Cdat.built == true) {
				MassAdder(Cdat);
				
			}
			break;
		case 4:
			PointMassData Pdat = new PointMassData();
			if (Pdat.built == true) {
				MassAdder(Pdat);
				
			}
			break;
		case 5:
			ParachuteData Padat = new ParachuteData();
			if (Padat.built == true) {
				MassAdder(Padat);
				
			}
			break;
		}
	}//GEN-LAST:event_MassPartSetActionPerformed
	
	private void MassAdder(RockPartsData part) {
		TheRocket.addMassPart(part, StageComboBox.getSelectedIndex());
		UpdateTree();
	}
	
	private void jMenuItem1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseReleased
	
	}//GEN-LAST:event_jMenuItem1MouseReleased
	
	private void jMenuItem2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseReleased
	
	
	}//GEN-LAST:event_jMenuItem2MouseReleased
	
	private void MotorCreationButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MotorCreationButtonMouseReleased
		// TODO add your handling code here:
	}//GEN-LAST:event_MotorCreationButtonMouseReleased
	
	private void MotorCreationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotorCreationButtonActionPerformed
		MotorData MD1 = new MotorData();
		MD1.EditMe();
		if (MD1.AddToList == true) {
			TheMotors.AddtoList(MD1);
		}
	}//GEN-LAST:event_MotorCreationButtonActionPerformed
	
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
		
		MotorData MD1 = new MotorData();
		JFileChooser fc = new JFileChooser();
		fc.setCurrentDirectory(PPL.MotorDir);
		int RetVal = fc.showOpenDialog(null);
		
		if (RetVal == fc.APPROVE_OPTION) {
			String Filename = fc.getSelectedFile().getPath();
			
			try {
				RWmotorXML Rxml = new RWmotorXML(Filename);
				Rxml.ReadXMLtoMotor();
				MD1 = Rxml.MotDat;
				MD1.CalculateSimpson();
				TheMotors.AddtoList(MD1);
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, ("Loading " + Filename + " failed. \nSystem msg: " + e));
			}
			
		}
		
		
	}//GEN-LAST:event_jButton3ActionPerformed
	
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		MotorData MD = (MotorData) jList1.getSelectedValue();
		MD.EditMe();
	}//GEN-LAST:event_jButton2ActionPerformed
	
	private void jList1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jList1FocusGained
		/*if(!jList1.isSelectionEmpty())
		{
		jButton2.setEnabled(true);
		}
		else
		{
		jButton2.setEnabled(false);
		}*/
	}//GEN-LAST:event_jList1FocusGained
	
	private void jList1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jList1FocusLost
		/*if(!jList1.isSelectionEmpty())
		{
		jButton2.setEnabled(true);
		}
		else
		{
		jButton2.setEnabled(false);
		}*/
	}//GEN-LAST:event_jList1FocusLost
	
	private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
		if (!jList1.isSelectionEmpty()) {
			jButton2.setEnabled(true);
		} else {
			jButton2.setEnabled(false);
		}
	}//GEN-LAST:event_jList1ValueChanged
	
	private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
		MotorData MD = (MotorData) jList1.getSelectedValue();
		MD.EditMe();
	}//GEN-LAST:event_jMenuItem3ActionPerformed
	
	private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
		TheMotors.RemoveFromList(jList1.getSelectedIndex());
	}//GEN-LAST:event_jMenuItem4ActionPerformed
	
	private void jList1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseReleased
		maybeShowPopup2(evt);
	}//GEN-LAST:event_jList1MouseReleased
	
	private void jList1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MousePressed
		maybeShowPopup2(evt);
	}//GEN-LAST:event_jList1MousePressed
	
	private void ConfigSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfigSaveButtonActionPerformed
		
		if (CheckForLaunch()) {
			/*JFileChooser fc = new JFileChooser();
			int RetVal = fc.showSaveDialog(null);
			if(RetVal == fc.APPROVE_OPTION)
			{
			RWsiminXML WriteSim = new RWsiminXML(fc.getSelectedFile().getPath());
			int mIts=1;
			if(MonteCarloRadio.isSelected()){
			    mIts = Integer.parseInt(MonteCarloField.getText());
			}
			WriteSim.WriteSimDataToXML(TheRocket,TheAtmosphere,LaunchPadSet,MonteCarloRadio.isSelected(),mIts,ParachuteFailChk.isSelected());
			String[] Command = {"/home/simon/Ubuntu One/NetBeansProject/RocketC/dist/Debug/GNU-Linux-x86/rocketc", fc.getSelectedFile().getPath()};
			try{
			    Process p = Runtime.getRuntime().exec(Command);
			    p.waitFor();
			}
			catch(Exception e){
			    JOptionPane.showMessageDialog(null,("Error running the rocket simulator. System message:" + e.getMessage()));
			}
			
			LoadOutPutData();
			}*/
			int mIts = 1;
			if (MonteCarloRadio.isSelected()) {
				mIts = Integer.parseInt(MonteCarloField.getText());
			}
			boolean ballisticF = !TheRocket.Stages.elementAt(0).hasParachutes();//TODO this needs to be made more explicit for each stage.
			PlotLauncher ThrowFigures = new PlotLauncher(PPL.InstallationDir.getPath());
			SimulatorInterface RocketCconnect = new SimulatorInterface(PPL, ThrowFigures);
			RocketCconnect.RunSim(TheRocket, TheAtmosphere, LaunchPadSet, MonteCarloRadio.isSelected(), ballisticF, mIts);
			if (RocketCconnect.Success) {
				LoadOutPutData(RocketCconnect);
			}
			
			
		}
	}//GEN-LAST:event_ConfigSaveButtonActionPerformed
	
	private void LoadOutPutData(SimulatorInterface rcon) {
		String fname = rcon.SimulationOut.getPath();
		dataTable1.LoadDataFile(fname);
		dataTable1.MakeDataTable();
		dataTable1.MakeSummaryData();
		jTabbedPane2.setSelectedIndex(4);
	}
	
	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
		AtmosphereData AD1 = new AtmosphereData();
		AD1.EditMeRaw();
		if (AD1.AddToList) {
			Atmospheres.AddtoList(AD1);
		}
	}//GEN-LAST:event_jButton5ActionPerformed
	
	private void MassPartChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MassPartChooseActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_MassPartChooseActionPerformed
	
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		MotorData MdNow = (MotorData) jComboBox1.getSelectedItem();
		RocketMotor rMot = new RocketMotor(MdNow, 0);
		rMot.EditMe();
		if (rMot.built) {
			TheRocket.addMotor(rMot, StageComboBox.getSelectedIndex());
			UpdateTree();
		}
	}//GEN-LAST:event_jButton1ActionPerformed
	
	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
	
	}//GEN-LAST:event_jComboBox1ActionPerformed
	
	private void WriteToFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WriteToFileButtonActionPerformed
		JFileChooser fc = new JFileChooser();
		fc.setCurrentDirectory(PPL.DesignDir);
		int RetVal = fc.showSaveDialog(null);
		
		if (RetVal == fc.APPROVE_OPTION) {
			String Filename = fc.getSelectedFile().getPath();
			RWdesignXML designWrite = new RWdesignXML(Filename);
			designWrite.WriteDesign(TheRocket);
		}
		
		
	}//GEN-LAST:event_WriteToFileButtonActionPerformed
	
	private void DesignLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesignLoadButtonActionPerformed
		JFileChooser fc = new JFileChooser();
		fc.setCurrentDirectory(PPL.DesignDir);
		int RetVal = fc.showOpenDialog(null);
		
		if (RetVal == fc.APPROVE_OPTION) {
			String Filename = fc.getSelectedFile().getPath();
			try {
				RWdesignXML designRead = new RWdesignXML(Filename);
				TheRocket = designRead.ReadDesign();
				UpdateTree();
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, ("Loading " + Filename + " failed. \nSystem msg: " + e));
			}
		}
		
	}//GEN-LAST:event_DesignLoadButtonActionPerformed
	
	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
		JFileChooser fc = new JFileChooser();
		fc.setCurrentDirectory(PPL.AtmosDir);
		int RetVal = fc.showOpenDialog(null);
		
		if (RetVal == fc.APPROVE_OPTION) {
			String Filename = fc.getSelectedFile().getPath();
			try {
				RWatmosXML atmosdata = new RWatmosXML(Filename);
				atmosdata.ReadXMLtoAtmos();
				Atmospheres.AddtoList(atmosdata.Atmosdat);
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, ("Loading " + Filename + " failed. \nSystem msg: " + e));
			}
		}
	}//GEN-LAST:event_jButton7ActionPerformed
	
	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
		AtmosphereData AD = (AtmosphereData) jList2.getSelectedValue();
		AD.EditMeRaw();
	}//GEN-LAST:event_jButton6ActionPerformed
	
	private void MonteCarloRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonteCarloRadioActionPerformed
		
		MonteCarloField.setEnabled(MonteCarloRadio.isSelected());
		
	}//GEN-LAST:event_MonteCarloRadioActionPerformed
	
	private void LaunchRailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LaunchRailFieldFocusLost
		ReadLaunchData();
	}//GEN-LAST:event_LaunchRailFieldFocusLost
	
	private void AzimuthFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AzimuthFieldFocusLost
		ReadLaunchData();
	}//GEN-LAST:event_AzimuthFieldFocusLost
	
	private void DeclinationFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DeclinationFieldFocusLost
		ReadLaunchData();
	}//GEN-LAST:event_DeclinationFieldFocusLost
	
	private void MotorPaneTipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotorPaneTipsActionPerformed
		Tips tDiag = new Tips(null, true);
		tDiag.setTipTxt(
				"Motor Design Tab \n\n Use this tab to specify the parameters of your rocket motors  and to load saved rocket motor parameters. Loaded motors appear in the pane, any motors in this list will be available for selection in the Rocket Design tab.");
		tDiag.setVisible(true);
	}//GEN-LAST:event_MotorPaneTipsActionPerformed
	
	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
		Tips tDiag = new Tips(null, true);
		tDiag.setTipTxt(
				"Rocket Design Tab \n\n Use this tab to design your rocket. You can build rockets up from component parts. There are three classes of part: Body Parts are parts that form the external airframe of the rocket. Internal Parts are any parts that are not in contact with the air outside the rocket, with the exception of the Motor Part, which is the third class. \n\n Use the combo boxes to select the part you wish to add and click \"Add\" to call up a window that allows you to specify the parameters of the part. Added parts will appear in the Rocket tree on the left. Right click parts in the tree to either edit or delete them.\n\n Designs can be saved and loaded using the buttons on the right. Loading a design will overwrite any parts currently in the rocket tree.");
		tDiag.setVisible(true);
	}//GEN-LAST:event_jButton4ActionPerformed
	
	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
		Tips tDiag = new Tips(null, true);
		tDiag.setTipTxt(
				"Wind Conditions Tab \n\n Use this tab to specify the atmospheric conditions at your rocket launch site. You can create a new profile or load a previously saved one. Loaded profiles appear in the pane, any profiles in this list will be available for selection in the Launcher tab.");
		tDiag.setVisible(true);
	}//GEN-LAST:event_jButton8ActionPerformed
	
	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
		Tips tDiag = new Tips(null, true);
		tDiag.setTipTxt(
				"Launcher Tab \n\n Use this tab to specify the conditions at the launch site and to launch the rocket specified in the Rocket tree on the left. The azimuth and declination angles define where the launch tower is pointing. Azimuth is the horizontal angle in degrees measured clockwise from 0 at due North. Declination is the vertical angle measured from 0 at \"straight up\"\n\n Select Monte Carlo to run multiple stochastic rocket flights. Note that selecting a large number of flights may require significant run times. ");
		tDiag.setVisible(true);
	}//GEN-LAST:event_jButton9ActionPerformed
	
	private void LeafIsSelected(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_LeafIsSelected
		// TODO add your handling code here:
		
	}//GEN-LAST:event_LeafIsSelected
	
	private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
		// TODO add your handling code here:4
	}//GEN-LAST:event_jTree1MouseClicked
	
	private void jTree1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseReleased
		EditPartButton.setEnabled(false);
		DeletePartButton.setEnabled(false);
		int SelNum = jTree1.getRowForLocation(evt.getX(), evt.getY());
		javax.swing.tree.TreePath TP = jTree1.getPathForRow(SelNum);
		try {
			DefaultMutableTreeNode TheLeaf = (DefaultMutableTreeNode) TP.getLastPathComponent();
			if (TheLeaf.toString().contains("Booster")) {
				DeletePartButton.setEnabled(true);
				jMenuItem1.setEnabled(false);
				jMenuItem2.setEnabled(true);
				if (SelNum != -1) {
					maybeShowPopup(evt);
				}
				
			} else {
				jMenuItem1.setEnabled(true);
				RockPartsData ThePart = (RockPartsData) TheLeaf.getUserObject();
				EditPartButton.setEnabled(true);
				if (ThePart.toString().contains("Stage Transition")) {
					jMenuItem2.setEnabled(false);
					
				} else {
					jMenuItem2.setEnabled(true);
					DeletePartButton.setEnabled(true);
				}
				if (SelNum != -1) {
					maybeShowPopup(evt);
				}
			}
		} catch (Exception e) {
		}
	}//GEN-LAST:event_jTree1MouseReleased
	
	private void jTree1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MousePressed
		EditPartButton.setEnabled(false);
		DeletePartButton.setEnabled(false);
		int SelNum = jTree1.getRowForLocation(evt.getX(), evt.getY());
		javax.swing.tree.TreePath TP = jTree1.getPathForRow(SelNum);
		try {
			DefaultMutableTreeNode TheLeaf = (DefaultMutableTreeNode) TP.getLastPathComponent();
			if (TheLeaf.toString().contains("Booster")) {
				DeletePartButton.setEnabled(true);
				jMenuItem1.setEnabled(false);
				jMenuItem2.setEnabled(true);
				if (SelNum != -1) {
					maybeShowPopup(evt);
				}
				
			} else {
				jMenuItem1.setEnabled(true);
				RockPartsData ThePart = (RockPartsData) TheLeaf.getUserObject();
				EditPartButton.setEnabled(true);
				if (ThePart.toString().contains("Stage Transition")) {
					jMenuItem2.setEnabled(false);
					
				} else {
					jMenuItem2.setEnabled(true);
					DeletePartButton.setEnabled(true);
				}
				if (SelNum != -1) {
					maybeShowPopup(evt);
				}
			}
		} catch (Exception e) {
		}
		LastTreeRow = SelNum;
	}//GEN-LAST:event_jTree1MousePressed
	
	private void BoosterStageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoosterStageButtonActionPerformed
		if (StageComboBox.getItemCount() < 2) {
			TheRocket.addTransition();
			TheRocket.addNewStage();
			UpdateTree();
		} else {
			JOptionPane.showMessageDialog(null, "Three+ stage rocket simulation is not yet available, but is under development.");
		}
	}//GEN-LAST:event_BoosterStageButtonActionPerformed
	
	private void jTabbedPane2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane2FocusGained
	
	}//GEN-LAST:event_jTabbedPane2FocusGained
	
	private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
		DeletePart();
	}//GEN-LAST:event_jMenuItem2ActionPerformed
	
	private void DeletePart() {
		if (jMenuItem2.isEnabled()) {
			javax.swing.tree.TreePath TP = jTree1.getPathForRow(LastTreeRow);
			DefaultMutableTreeNode TheLeaf = (DefaultMutableTreeNode) TP.getLastPathComponent();
			javax.swing.tree.MutableTreeNode Parent = (javax.swing.tree.MutableTreeNode) (TheLeaf.getParent());
			if (Parent != null) {
				if (TheLeaf.toString().contains("Booster")) {
					TheRocket.RemoveStage(TheLeaf);
				} else {
					TheRocket.RemovePart(TheLeaf);
				}
			}
			UpdateTree();
		}
	}
	
	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
		EditPart();
	}//GEN-LAST:event_jMenuItem1ActionPerformed
	
	private void EditPart() {
		if (jMenuItem1.isEnabled()) {
			javax.swing.tree.TreePath TP = jTree1.getPathForRow(LastTreeRow);
			DefaultMutableTreeNode TheLeaf = (DefaultMutableTreeNode) TP.getLastPathComponent();
			RockPartsData ThePart = (RockPartsData) TheLeaf.getUserObject();
			ThePart.EditMe();
		}
	}
	
	private void jPanel1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusLost
		//TODO
	}//GEN-LAST:event_jPanel1FocusLost
	
	private void jTree1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTree1FocusLost
		//EditPartButton.setEnabled(false);
		//EditPartButton.setEnabled(true);
	}//GEN-LAST:event_jTree1FocusLost
	
	private void EditPartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPartButtonActionPerformed
		EditPart();
	}//GEN-LAST:event_EditPartButtonActionPerformed
	
	private void DeletePartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletePartButtonActionPerformed
		DeletePart();
	}//GEN-LAST:event_DeletePartButtonActionPerformed
	
	private void jList2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MousePressed
		MaybeShowPopupAtmos(evt);
	}//GEN-LAST:event_jList2MousePressed
	
	private void EditAtmosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditAtmosActionPerformed
		AtmosphereData AD = (AtmosphereData) jList2.getSelectedValue();
		AD.EditMeRaw();
	}//GEN-LAST:event_EditAtmosActionPerformed
	
	private void AtmosDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtmosDeleteActionPerformed
		Atmospheres.RemoveFromList(jList2.getSelectedIndex());
	}//GEN-LAST:event_AtmosDeleteActionPerformed
	
	private void AtmosphereComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtmosphereComboBoxActionPerformed
		ReadLaunchData();
	}//GEN-LAST:event_AtmosphereComboBoxActionPerformed
	
	private void maybeShowPopup(java.awt.event.MouseEvent evt) {
		if (evt.isPopupTrigger()) {
			
			
			TreeRightClickMenu.show(evt.getComponent(), evt.getX(), evt.getY());
		}
	}
	
	private void maybeShowPopup2(java.awt.event.MouseEvent evt) {
		if (evt.isPopupTrigger()) {
			
			
			ListRightClickMenu.show(evt.getComponent(), evt.getX(), evt.getY());
		}
	}
	
	private void MaybeShowPopupAtmos(java.awt.event.MouseEvent evt) {
		if (evt.isPopupTrigger()) {
			AtmosListMenu.show(evt.getComponent(), evt.getX(), evt.getY());
		}
	}
	
	private void ReadLaunchData() {
		TheAtmosphere = (AtmosphereData) AtmosphereComboBox.getSelectedItem();
		LaunchPadSet.SetData(LaunchRailField, AzimuthField, DeclinationField);
	}
	
	private boolean CheckForLaunch() {
		boolean OK;
		if (TheRocket.Stages.firstElement().isEmpty()) {
			OK = false;
			JOptionPane.showMessageDialog(null, ("No Main Stage design found"));
		} else if (!TheRocket.Stages.lastElement().hasMotor()) {
			OK = false;
			JOptionPane.showMessageDialog(null, ("The Rocket needs a motor"));
		} else if (!LaunchPadSet.Built) {
			OK = false;
			JOptionPane.showMessageDialog(null, ("No launch parameters found"));
		} else if (!TheAtmosphere.built) {
			OK = false;
			JOptionPane.showMessageDialog(null, ("No Atmosphere data found"));
		} else {
			OK = true;
		}
		
		
		return (OK);
		
	}
	
	/**
	* @param args the command line arguments
	*/
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				// Set System L&F
				try {
					UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
				} catch (UnsupportedLookAndFeelException e) {
					// handle exception
				} catch (ClassNotFoundException e) {
					// handle exception
				} catch (InstantiationException e) {
					// handle exception
				} catch (IllegalAccessException e) {
					// handle exception
				}
				
				
				MainForm CRSform = new MainForm();
				CRSform.setVisible(true);
			}
		});
	}
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel AddBodyLabel;
	private javax.swing.JLabel AddMassLabel;
	private javax.swing.JMenuItem AtmosDelete;
	private javax.swing.JPopupMenu AtmosListMenu;
	private javax.swing.JComboBox AtmosphereComboBox;
	private javax.swing.JPanel AtmospherePanel;
	private javax.swing.JTextField AzimuthField;
	private javax.swing.JComboBox BodyPartChoose;
	private javax.swing.JButton BodyPartSet;
	private javax.swing.JButton BoosterStageButton;
	private javax.swing.JButton ConfigSaveButton;
	private javax.swing.JTextField DeclinationField;
	private javax.swing.JButton DeletePartButton;
	private javax.swing.JButton DesignLoadButton;
	private javax.swing.JMenuItem EditAtmos;
	private javax.swing.JButton EditPartButton;
	private javax.swing.JTextField LaunchRailField;
	private javax.swing.JPopupMenu ListRightClickMenu;
	private javax.swing.JComboBox MassPartChoose;
	private javax.swing.JButton MassPartSet;
	private javax.swing.JTextField MonteCarloField;
	private javax.swing.JRadioButton MonteCarloRadio;
	private javax.swing.JButton MotorCreationButton;
	private javax.swing.JPanel MotorDesignPanel;
	private javax.swing.JButton MotorPaneTips;
	private javax.swing.JLabel PartSelectFrameTitle;
	private javax.swing.JPanel PlotterPanel;
	private javax.swing.JPanel RocketDesignPanel;
	private javax.swing.JPanel SimulationPanel;
	private javax.swing.JComboBox StageComboBox;
	private javax.swing.JPopupMenu TreeRightClickMenu;
	private javax.swing.JButton WriteToFileButton;
	private net.sf.openrocket.camrocksim.DataTable dataTable1;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JList jList1;
	private javax.swing.JList jList2;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTabbedPane jTabbedPane2;
	private javax.swing.JTree jTree1;
	// End of variables declaration//GEN-END:variables
	
	
	//***************************************************
	//My additional functions
	//***************************************************
	
	//Function to update Tree
	private void UpdateTree() {
		jTree1.setModel(TheRocket.RocketTree);
		StageComboBox.setModel(TheRocket.StageCombo);
		
	}
	
}
