/*
%## Copyright (C) 2010, 2016 S.Box
%## 
%## This program is free software; you can redistribute it and/or modify
%## it under the terms of the GNU General Public License as published by
%## the Free Software Foundation; either version 2 of the License, or
%## (at your option) any later version.
%## 
%## This program is distributed in the hope that it will be useful,
%## but WITHOUT ANY WARRANTY; without even the implied warranty of
%## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%## GNU General Public License for more details.
%## 
%## You should have received a copy of the GNU General Public License
%## along with this program; if not, write to the Free Software
%## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

%## NoseConeDialog.java

%## Author: S.Box
%## Created: 2010-05-27
/*
 * ConeDialog.java
 *
 * Created on 14 April 2009, 17:02
 */

package net.sf.openrocket.camrocksim;

import java.util.Vector;

import javax.swing.JOptionPane;

/**
 *
 * @author  simon
 */
public class NoseConeDialog extends javax.swing.JDialog {
	//*Class Members
	
	int ShapeI;
	double Length, Diameter, Mass, Position;
	boolean ReadOk;
	String Name;
	
	/** Creates new form ConeDialog */
	public NoseConeDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		
		NoseTitleLabel = new javax.swing.JLabel();
		NoseLengthLabel = new javax.swing.JLabel();
		NoseDiameterLabel = new javax.swing.JLabel();
		NoseMassLabel = new javax.swing.JLabel();
		NosePositionLabel = new javax.swing.JLabel();
		NoseLengthBox = new javax.swing.JTextField();
		NoseDiameterBox = new javax.swing.JTextField();
		NoseMassBox = new javax.swing.JTextField();
		NosePositionBox = new javax.swing.JTextField();
		NoseLengthDim = new javax.swing.JLabel();
		NoseDiameterDim = new javax.swing.JLabel();
		NoseMassDim = new javax.swing.JLabel();
		NosePositionDim = new javax.swing.JLabel();
		AddNoseDataButton = new javax.swing.JButton();
		NoseCancelButton = new javax.swing.JButton();
		NoseShapeLabel = new javax.swing.JLabel();
		NoseShapeBox = new javax.swing.JComboBox();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Cone data dialog");
		
		NoseTitleLabel.setText("Set nose cone specifications");
		
		NoseLengthLabel.setText("Length");
		
		NoseDiameterLabel.setText("Base Diameter");
		
		NoseMassLabel.setText("Mass");
		
		NosePositionLabel.setText("Position");
		
		NoseLengthBox.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				NoseLengthBoxFocusGained(evt);
			}
			
			public void focusLost(java.awt.event.FocusEvent evt) {
				NoseLengthBoxFocusLost(evt);
			}
		});
		
		NoseDiameterBox.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				NoseDiameterBoxFocusGained(evt);
			}
			
			public void focusLost(java.awt.event.FocusEvent evt) {
				NoseDiameterBoxFocusLost(evt);
			}
		});
		
		NoseMassBox.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				NoseMassBoxFocusGained(evt);
			}
			
			public void focusLost(java.awt.event.FocusEvent evt) {
				NoseMassBoxFocusLost(evt);
			}
		});
		
		NosePositionBox.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				NosePositionBoxFocusGained(evt);
			}
			
			public void focusLost(java.awt.event.FocusEvent evt) {
				NosePositionBoxFocusLost(evt);
			}
		});
		
		NoseLengthDim.setText("m");
		
		NoseDiameterDim.setText("m");
		
		NoseMassDim.setText("kg");
		
		NosePositionDim.setText("m");
		
		AddNoseDataButton.setText("Add");
		AddNoseDataButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				AddNoseDataButtonActionPerformed(evt);
			}
		});
		
		NoseCancelButton.setText("Cancel");
		NoseCancelButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				NoseCancelButtonActionPerformed(evt);
			}
		});
		
		NoseShapeLabel.setText("Shape");
		
		NoseShapeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ogive", "Conical", "Parabolic" }));
		
		jLabel1.setText("Name");
		
		jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				jTextField1FocusLost(evt);
			}
		});
		
		jButton1.setText("?");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addContainerGap()
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(NoseTitleLabel)
														.addComponent(jLabel1)
														.addGroup(layout.createSequentialGroup()
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(NoseLengthLabel)
																		.addComponent(NoseDiameterLabel)
																		.addComponent(NoseMassLabel)
																		.addComponent(NosePositionLabel)
																		.addComponent(NoseShapeLabel))
																.addGap(35, 35, 35)
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
																		.addComponent(NoseShapeBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																		.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
																				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
																						.addComponent(NosePositionBox, javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(NoseMassBox, javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(NoseDiameterBox, javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(NoseLengthBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE,
																								86, javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(NoseMassDim)
																						.addComponent(NosePositionDim)
																						.addComponent(NoseDiameterDim)
																						.addComponent(NoseLengthDim)))
																		.addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))))
										.addGroup(layout.createSequentialGroup()
												.addGap(41, 41, 41)
												.addComponent(AddNoseDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addComponent(NoseCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(61, Short.MAX_VALUE)));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(NoseTitleLabel)
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel1)
										.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(NoseShapeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(NoseShapeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(NoseLengthDim)
										.addComponent(NoseLengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(NoseLengthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(NoseDiameterLabel)
										.addComponent(NoseDiameterDim)
										.addComponent(NoseDiameterBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(NoseMassLabel)
										.addComponent(NoseMassDim, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(NoseMassBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(NosePositionLabel)
										.addComponent(NosePositionDim)
										.addComponent(NosePositionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(AddNoseDataButton)
										.addComponent(NoseCancelButton)
										.addComponent(jButton1))
								.addGap(22, 22, 22)));
		
		pack();
	}// </editor-fold>//GEN-END:initComponents
	
	private void NoseLengthBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NoseLengthBoxFocusLost
		//Function to test the validity of the user input
		TestUserTextInput LengthTest = new TestUserTextInput(NoseLengthBox);
		Length = LengthTest.TestDouble();
		NoseLengthBox = LengthTest.InputField;
	}//GEN-LAST:event_NoseLengthBoxFocusLost
	
	private void NoseDiameterBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NoseDiameterBoxFocusLost
		//Function to test the validity of the user input
		TestUserTextInput DiameterTest = new TestUserTextInput(NoseDiameterBox);
		Diameter = DiameterTest.TestDouble();
		NoseDiameterBox = DiameterTest.InputField;
	}//GEN-LAST:event_NoseDiameterBoxFocusLost
	
	private void NoseMassBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NoseMassBoxFocusLost
		//Function to test the validity of the user input
		TestUserTextInput MassTest = new TestUserTextInput(NoseMassBox);
		Mass = MassTest.TestDouble();
		NoseMassBox = MassTest.InputField;
	}//GEN-LAST:event_NoseMassBoxFocusLost
	
	private void NosePositionBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NosePositionBoxFocusLost
		//Function to test the validity of the user input
		TestUserTextInput PositionTest = new TestUserTextInput(NosePositionBox);
		Position = PositionTest.TestDouble();
		NosePositionBox = PositionTest.InputField;
	}//GEN-LAST:event_NosePositionBoxFocusLost
	
	private void NoseCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoseCancelButtonActionPerformed
		// TODO add your handling code here:
		this.dispose();
	}//GEN-LAST:event_NoseCancelButtonActionPerformed
	
	private void AddNoseDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNoseDataButtonActionPerformed
		// TODO add your handling code here:
		boolean Goer = CheckValidity();
		if (Goer == true) {
			ReadOk = true;
			ShapeI = NoseShapeBox.getSelectedIndex();
			this.dispose();
		} else {
			JOptionPane.showMessageDialog(null, ("Something is wrong with the data that you entered"));
		}
		
	}//GEN-LAST:event_AddNoseDataButtonActionPerformed
	
	private void NoseLengthBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NoseLengthBoxFocusGained
		// TODO add your handling code here:
		NoseLengthBox.setForeground(java.awt.Color.BLACK);
	}//GEN-LAST:event_NoseLengthBoxFocusGained
	
	private void NoseDiameterBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NoseDiameterBoxFocusGained
		// TODO add your handling code here:
		NoseDiameterBox.setForeground(java.awt.Color.BLACK);
	}//GEN-LAST:event_NoseDiameterBoxFocusGained
	
	private void NoseMassBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NoseMassBoxFocusGained
		// TODO add your handling code here:
		NoseMassBox.setForeground(java.awt.Color.BLACK);
	}//GEN-LAST:event_NoseMassBoxFocusGained
	
	private void NosePositionBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NosePositionBoxFocusGained
		// TODO add your handling code here:
		NosePositionBox.setForeground(java.awt.Color.BLACK);
	}//GEN-LAST:event_NosePositionBoxFocusGained
	
	private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
		// TODO add your handling code here:
		Name = jTextField1.getText();
	}//GEN-LAST:event_jTextField1FocusLost
	
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		Tips tDiag = new Tips(null, true);
		tDiag.setTipTxt(
				"Nose Cone Settings \n\n Use this window to specify the parameters of the Nose. Position is the distance, along the rocket's axis, from the nose tip to the foremost edge of the part, usually zero in this case.");
		tDiag.setVisible(true);
	}//GEN-LAST:event_jButton1ActionPerformed
	
	
	private boolean CheckValidity() {
		boolean answer;
		Vector<javax.swing.JTextField> FieldsList = new Vector<javax.swing.JTextField>();
		FieldsList.add(NoseLengthBox);
		FieldsList.add(NoseDiameterBox);
		FieldsList.add(NoseMassBox);
		FieldsList.add(NosePositionBox);
		
		TestUserTextInput TUI1 = new TestUserTextInput(FieldsList);
		answer = TUI1.TestDoubleList();
		return (answer);
	}
	
	/**
	* @param args the command line arguments
	*/
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				ConeDialog dialog = new ConeDialog(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}
	
	public void FillFields(double d1, double d2, double d3, double d4, int ShapeID, String S1) {
		Length = d1;
		Diameter = d2;
		Position = d3;
		Mass = d4;
		ShapeI = ShapeID;
		Name = S1;
		
		NoseLengthBox.setText(Double.toString(Length));
		NoseDiameterBox.setText(Double.toString(Diameter));
		NosePositionBox.setText(Double.toString(Position));
		NoseMassBox.setText(Double.toString(Mass));
		NoseShapeBox.setSelectedIndex(ShapeI);
		jTextField1.setText(Name);
		
	}
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton AddNoseDataButton;
	private javax.swing.JButton NoseCancelButton;
	private javax.swing.JTextField NoseDiameterBox;
	private javax.swing.JLabel NoseDiameterDim;
	private javax.swing.JLabel NoseDiameterLabel;
	private javax.swing.JTextField NoseLengthBox;
	private javax.swing.JLabel NoseLengthDim;
	private javax.swing.JLabel NoseLengthLabel;
	private javax.swing.JTextField NoseMassBox;
	private javax.swing.JLabel NoseMassDim;
	private javax.swing.JLabel NoseMassLabel;
	private javax.swing.JTextField NosePositionBox;
	private javax.swing.JLabel NosePositionDim;
	private javax.swing.JLabel NosePositionLabel;
	private javax.swing.JComboBox NoseShapeBox;
	private javax.swing.JLabel NoseShapeLabel;
	private javax.swing.JLabel NoseTitleLabel;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables
	
}
